/*
Makes use of no third-party code (for better or worse)

Copyright (c) 2014

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
(function(){var M,S,v=480,H=["hunger","health","sanity"],sa={hunger:!0,health:!0,sanity:!0},ta={bestHunger:!0,bestHealth:!0,bestSanity:!0},m=1*v,p=3*v,g=6*v,f=10*v,u=15*v,C=20*v,G=40*v,n=2*v,ua=v/16*.6666,T={raw:1,dried:1,cooked:1,recipe:1},F=T,Y=[],B=7,x={vanilla:{name:"Vanilla",img:"vanilla.png",bit:1,mask:1,color:"#ff592e"},giants:{name:"Reign of Giants",img:"reign_of_giants.png",bit:2,mask:3,color:"#b857c6"},shipwrecked:{name:"Shipwrecked",img:"shipwrecked.png",bit:4,mask:7,color:"#50c1cc"},together:{name:"Don't Starve Together",
img:"together.png",bit:8,mask:11,color:"#c0c0c0"},warly:{name:"Warly",img:"warly.png",bit:16,mask:23,multipliers:{raw:.7,dried:.8,cooked:.9,recipe:1.2}}},W=function(a){F={};for(d in T)T.hasOwnProperty(d)&&(F[d]=T[d]);B=a;for(var d=0;d<N.childNodes.length;d++){a=N.childNodes[d];var b=x[a.dataset.mode];a.className=0!==(B&b.bit)?"enabled":"";if(b.multipliers&&0!==(B&b.bit))for(var c in b.multipliers)b.multipliers.hasOwnProperty(c)&&(F[c]*=b.multipliers[c])}for(d=0;d<Y.length;d++)Y[d]();c=["together",
"shipwrecked","giants","vanilla"];for(d=0;d<c.length;d++)if(0!==(B&x[c[d]].bit)){document.getElementsByTagName("BODY")[0].style["background-color"]=x[c[d]].color;break}},q={acorn:{name:"Birchnut",uncookable:!0,perish:C,stack:40,mode:"giants"},acorn_cooked:{name:"Roasted Birchnut",ideal:!0,seed:1,hunger:9.375,health:1,sanity:0,perish:g,stack:40,mode:"giants"},butter:{name:"Butter",fat:1,dairy:1,health:40,hunger:25,sanity:0,perish:G,stack:40},butterflywings:{name:"Butterfly Wings",isveggie:!0,decoration:2,
health:8,hunger:9.375,sanity:0,perish:g,stack:40},cactusflower:{name:"Cactus Flower",veggie:.5,hunger:12.5,health:8,sanity:5,perish:p,stack:40,mode:"giants"},deerclopseyeball:{name:"Deerclops Eyeball",uncookable:!0,health:60,hunger:75,sanity:-15},bird_egg:{name:"Egg",egg:1,health:0,hunger:9.375,sanity:0,perish:f,stack:40,rot:"rottenegg"},bird_egg_cooked:{name:"Cooked Egg",egg:1,precook:1,health:0,hunger:12.5,sanity:0,perish:g,stack:40},rottenegg:{name:"Rotten Egg",uncookable:!0,health:-1,hunger:-10,
sanity:0,stack:40},cutlichen:{name:"Lichen",isveggie:!0,veggie:1,health:3,hunger:12.5,sanity:-5,perish:2*v},eel:{name:"Eel",ismeat:!0,meat:.5,fish:1,health:3,hunger:9.375,sanity:0,perish:p,stack:40,dry:"morsel_dried",drytime:v},eel_cooked:{name:"Cooked Eel",ismeat:!0,health:8,hunger:12.5,sanity:0,perish:g,stack:40},fish:{name:"Fish",ismeat:!0,meat:.5,fish:1,health:1,hunger:12.5,sanity:0,perish:p,stack:40,drytime:v,dry:"morsel_dried"},fish_cooked:{name:"Cooked Fish",ismeat:!0,meat:.5,fish:1,precook:1,
health:1,hunger:12.5,sanity:0,perish:g,stack:40},froglegs:{name:"Frog Legs",ismeat:!0,meat:.5,health:0,hunger:12.5,perish:g,sanity:-10,stack:40},froglegs_cooked:{name:"Cooked Frog Legs",ismeat:!0,meat:.5,precook:1,health:1,hunger:12.5,perish:f,sanity:0,stack:40},foliage:{name:"Foliage",uncookable:!0,health:1,hunger:0,sanity:0,perish:g,stack:40},goatmilk:{name:"Electric Milk",dairy:1,health:3,hunger:12.5,sanity:10,perish:g,stack:40,mode:"giants"},honey:{name:"Honey",sweetener:!0,health:3,hunger:9.375,
sanity:0,perish:G,stack:40},honeycomb:{name:"Honeycomb",sweetener:!0},ice:{name:"Ice",frozen:1,health:.5,hunger:2.34375,sanity:0,perish:p,stack:40,mode:"giants"},lightbulb:{name:"Light Bulb",health:1,hunger:0,sanity:0,perish:g,stack:40,uncookable:!0},mandrake:{name:"Mandrake",veggie:1,magic:1,health:60,hunger:75,sanity:0,stack:40},mandrake_cooked:{name:"Cooked Mandrake",uncookable:!0,veggie:1,magic:1,precook:1,health:100,hunger:150,sanity:0,stack:40},mole:{name:"Moleworm",ideal:!0,meat:.5,perish:2*
v,cook:"morsel_cooked",mode:"giants"},plantmeat:{name:"Leafy Meat",uncookable:!0,health:0,hunger:12.5,sanity:-10,perish:g,stack:40},plantmeat_cooked:{name:"Cooked Leafy Meat",uncookable:!0,health:1,hunger:18.75,sanity:0,perish:f,stack:40},monstermeat:{name:"Monster Meat",ismeat:!0,meat:1,monster:!0,health:-20,hunger:18.75,sanity:-15,perish:g,stack:20,dry:"monstermeat_dried",drytime:v},monstermeat_cooked:{name:"Cooked Monster Meat",ismeat:!0,meat:1,monster:!0,precook:1,health:-3,hunger:18.75,sanity:-10,
perish:u,stack:20},monstermeat_dried:{name:"Monster Jerky",ismeat:!0,meat:1,monster:!0,dried:1,health:-3,hunger:18.75,sanity:-5,perish:C,stack:20},meat:{name:"Meat",ismeat:!0,meat:1,health:1,hunger:25,sanity:-10,perish:g,stack:20,dry:"meat_dried",drytime:n},meat_cooked:{name:"Cooked Meat",ismeat:!0,meat:1,precook:1,health:3,hunger:25,sanity:0,perish:f,stack:20},meat_dried:{name:"Jerky",ismeat:!0,meat:1,dried:1,health:20,hunger:25,sanity:15,perish:C,stack:20},morsel:{name:"Morsel",ismeat:!0,meat:.5,
health:0,hunger:12.5,sanity:-10,perish:g,stack:40,drytime:v,dry:"morsel_dried"},morsel_cooked:{name:"Cooked Morsel",raw:"morsel",ismeat:!0,meat:.5,precook:1,health:1,hunger:12.5,sanity:0,perish:f,stack:40},morsel_dried:{name:"Small Jerky",wet:"morsel",ismeat:!0,meat:.5,dried:1,health:8,hunger:12.5,sanity:10,perish:C,stack:40},drumstick:{name:"Drumstick",ismeat:!0,ideal:!0,meat:.5,health:0,hunger:12.5,sanity:-10,perish:g,stack:20,drytime:v,dry:"morsel_dried"},drumstick_cooked:{name:"Fried Drumstick",
ismeat:!0,meat:.5,precook:1,health:1,hunger:12.5,sanity:0,perish:f,stack:20},batwing:{name:"Batilisk Wing",ismeat:!0,health:3,hunger:12.5,sanity:-10,perish:g,stack:40,drytime:n,dry:"morsel_dried",uncookable:!0},batwing_cooked:{name:"Cooked Batilisk Wing",ismeat:!0,health:8,hunger:18.75,sanity:0,perish:f,uncookable:!0},minotaurhorn:{name:"Guardian's Horn",uncookable:!0,ismeat:!0,health:60,hunger:75,sanity:-15},red_mushroom:{name:"Red Cap",basename:"CapRed",veggie:.5,ideal:!0,health:-20,hunger:12.5,
sanity:0,perish:f,stack:40},red_mushroom_cooked:{name:"Cooked Red Cap",veggie:.5,health:1,hunger:0,sanity:-10,perish:f,stack:40},green_mushroom:{name:"Green Cap",basename:"CapGreen",veggie:.5,ideal:!0,health:0,hunger:12.5,sanity:-50,perish:f,stack:40},green_mushroom_cooked:{name:"Cooked Green Cap",veggie:.5,health:-1,hunger:0,sanity:15,perish:f,stack:40},blue_mushroom:{name:"Blue Cap",basename:"CapBlue",veggie:.5,ideal:!0,health:20,hunger:12.5,sanity:-15,perish:f,stack:40},blue_mushroom_cooked:{name:"Cooked Blue Cap",
veggie:.5,health:-3,hunger:0,sanity:10,perish:f,stack:40},petals:{name:"Petals",uncookable:!0,health:1,hunger:0,sanity:0,perish:g,stack:40},petals_evil:{name:"Dark Petals",basename:"Petals.",uncookable:!0,health:0,hunger:0,sanity:-5,perish:g,stack:40},seeds:{name:"Seeds",uncookable:!0,health:0,hunger:4.6875,sanity:0,perish:G,stack:40},seeds_cooked:{name:"Toasted Seeds",uncookable:!0,health:1,hunger:4.6875,sanity:0,perish:f,stack:40},spoiled_food:{name:"Rot",uncookable:!0,health:-1,hunger:-10,sanity:0,
stack:40},tallbirdegg:{name:"Tallbird Egg",egg:4,health:3,hunger:25,sanity:0},tallbirdegg_cooked:{name:"Fried Tallbird Egg",egg:4,precook:1,health:0,hunger:37.5,sanity:0,perish:g},trunk_summer:{name:"Koalefant Trunk",uncookable:!0,ismeat:!0,health:30,hunger:37.5,sanity:0,perish:g,stack:20},trunk_summer_cooked:{name:"Koalefant Trunk Steak",uncookable:!0,ismeat:!0,health:40,hunger:75,sanity:0,perish:u,stack:20},twigs:{name:"Twigs",inedible:1},cavebanana:{name:"Banana",ideal:!0,isfruit:!0,fruit:1,health:1,
hunger:12.5,sanity:0,perish:f},cavebanana_cooked:{name:"Cooked Banana",isfruit:!0,fruit:1,precook:1,health:3,hunger:12.5,sanity:0,perish:g},carrot:{name:"Carrot",isveggie:!0,veggie:1,health:1,hunger:12.5,perish:f,sanity:0,stack:40},carrot_cooked:{name:"Roasted Carrot",isveggie:!0,veggie:1,precook:1,health:3,hunger:12.5,perish:g,sanity:0,stack:40},corn:{name:"Corn",ideal:!0,isveggie:!0,veggie:1,health:3,hunger:25,perish:f,sanity:0,stack:40},corn_cooked:{name:"Popcorn",isveggie:!0,veggie:1,precook:1,
health:3,hunger:12.5,perish:u,sanity:0,stack:40},pumpkin:{name:"Pumpkin",isveggie:!0,veggie:1,health:3,hunger:37.5,perish:f,sanity:0,stack:20},pumpkin_cooked:{name:"Hot Pumpkin",isveggie:!0,veggie:1,precook:1,health:8,hunger:37.5,perish:g,sanity:0,stack:20},eggplant:{name:"Eggplant",isveggie:!0,veggie:1,health:8,hunger:25,perish:f,sanity:0,stack:20},eggplant_cooked:{name:"Braised Eggplant",isveggie:!0,veggie:1,precook:1,health:20,hunger:25,perish:g,sanity:0,stack:20},durian:{name:"Durian",isfruit:!0,
monster:1,fruit:1,health:-3,hunger:25,perish:f,sanity:-5,stack:20},durian_cooked:{name:"Extra Smelly Durian",isfruit:!0,monster:1,fruit:1,precook:1,health:0,hunger:25,perish:g,sanity:-5,stack:20},pomegranate:{name:"Pomegranate",isfruit:!0,fruit:1,health:3,hunger:9.375,perish:g,sanity:0,stack:40},pomegranate_cooked:{name:"Sliced Pomegranate",isfruit:!0,fruit:1,precook:1,health:20,hunger:12.5,perish:p,sanity:0,stack:40},dragonfruit:{name:"Dragon Fruit",isfruit:!0,fruit:1,health:3,hunger:9.375,perish:g,
sanity:0,stack:40},dragonfruit_cooked:{name:"Prepared Dragon Fruit",isfruit:!0,fruit:1,precook:1,health:20,hunger:12.5,perish:p,sanity:0,stack:40},berries:{name:"Berries",isfruit:!0,fruit:.5,health:0,hunger:9.375,perish:g,sanity:0,stack:40},berries_cooked:{name:"Roasted Berries",isfruit:!0,fruit:.5,precook:1,health:1,hunger:12.5,perish:p,sanity:0,stack:40},cactusmeat:{name:"Cactus Flesh",ideal:!0,veggie:1,hunger:12.5,health:-3,perish:f,sanity:-5,stack:40,mode:"giants"},cactusmeat_cooked:{name:"Cooked Cactus Flesh",
veggie:1,hunger:12.5,health:1,perish:f,sanity:15,precook:1,stack:40,mode:"giants"},watermelon:{name:"Watermelon",fruit:1,ideal:!0,hunger:12.5,health:3,perish:g,sanity:5,stack:40,mode:"giants"},watermelon_cooked:{name:"Grilled Watermelon",fruit:1,hunger:12.5,health:1,perish:p,sanity:7.5,precook:1,stack:40,mode:"giants"},wormlight:{name:"Glow Berry",uncookable:!0,health:11,hunger:18.75,sanity:-10,perish:f,note:"Gives 90 seconds of light"},glommerfuel:{name:"Glommer's Goop",uncookable:!0,health:40,hunger:9.375,
sanity:-50,mode:"giants"},coral_brain:{name:"Brainy Matter",uncookable:!0,health:-10,hunger:10,sanity:50,perish:m,mode:"shipwrecked"},blubber:{name:"Blubber",uncookable:!0,health:10,hunger:10,sanity:0,perish:f,stack:10,mode:"shipwrecked"},seaweed:{name:"Seaweed",ideal:!0,veggie:1,health:1,hunger:9.375,sanity:-10,perish:g,stack:40,dry:"seaweed_dried",drytime:v,mode:"shipwrecked"},seaweed_cooked:{name:"Roasted Seaweed",veggie:1,health:3,hunger:9.375,sanity:0,perish:f,stack:40,mode:"shipwrecked"},seaweed_dried:{name:"Dried Seaweed",
veggie:1,health:3,hunger:12.5,sanity:0,perish:C,stack:40,mode:"shipwrecked"},sweet_potato:{name:"Sweet Potato",veggie:1,health:1,hunger:12.5,sanity:0,perish:f,stack:40,mode:"shipwrecked"},sweet_potato_cooked:{name:"Cooked Sweet Potato",veggie:1,health:3,hunger:12.5,sanity:0,perish:g,stack:40,mode:"shipwrecked"},coffeebeans:{name:"Coffee Beans",fruit:.5,health:0,hunger:9.375,sanity:0,perish:g,stack:40,mode:"shipwrecked"},coffeebeans_cooked:{name:"Roasted Coffee Beans",ideal:!0,fruit:1,health:0,hunger:9.375,
sanity:-5,perish:u,stack:40,note:"Gives 5 bonus speed (+83%) for 30 seconds",mode:"shipwrecked"},coconut_halved:{name:"Halved Coconut",basename:"Coconut.",fruit:1,fat:1,health:1,hunger:4.6875,sanity:0,perish:f,stack:40,cook:"coconut_cooked",mode:"shipwrecked"},coconut_cooked:{name:"Roasted Coconut",fruit:1,fat:1,health:1,hunger:9.375,sanity:0,perish:f,stack:40,mode:"shipwrecked"},doydoyegg:{name:"Doydoy Egg",egg:1,health:3,hunger:25,sanity:0,perish:f,mode:"shipwrecked"},doydoyegg_cooked:{name:"Fried Doydoy Egg",
egg:1,health:0,hunger:37.5,sanity:0,perish:g,mode:"shipwrecked"},tropical_fish:{name:"Tropical Fish",skip:!0,ismeat:!0,meat:.5,fish:1,health:1,hunger:12.5,sanity:0,perish:p,stack:40,cook:"fish_raw_small_cooked",dry:"morsel_dried",drytime:v,mode:"shipwrecked"},fish_raw:{name:"Raw Fish",meat:.5,fish:1,health:1,hunger:25,sanity:0,perish:p,stack:40,cook:"fish_med_cooked",dry:"meat_dried",drytime:v,mode:"shipwrecked"},fish_med:{name:"Dead Dogfish",meat:.5,fish:1,health:1,hunger:25,sanity:0,perish:g,stack:40,
rot:"spoiled_fish",dry:"meat_dried",drytime:v,mode:"shipwrecked"},dead_swordfish:{name:"Swordfish",uncookable:!0,health:1,hunger:25,sanity:0,perish:g,stack:40,cook:"fish_med_cooked",rot:"spoiled_fish",dry:"meat_dried",drytime:v,mode:"shipwrecked"},fish_med_cooked:{name:"Fish Steak",meat:.5,fish:1,health:20,hunger:25,sanity:0,perish:g,stack:40,mode:"shipwrecked"},shark_fin:{name:"Shark Fin",meat:.5,fish:1,health:20,hunger:25,sanity:-15,perish:g,stack:10,mode:"shipwrecked"},limpets:{name:"Limpets",
ideal:!0,fish:.5,health:0,hunger:12.5,sanity:-10,perish:g,stack:40,mode:"shipwrecked"},limpets_cooked:{name:"Cooked Limpets",fish:.5,health:1,hunger:12.5,sanity:0,perish:f,stack:40,mode:"shipwrecked"},mussel:{name:"Mussel",fish:.5,health:0,hunger:12.5,sanity:-10,perish:p,stack:40,mode:"shipwrecked"},mussel_cooked:{name:"Cooked Mussel",fish:.5,health:1,hunger:12.5,sanity:0,perish:p,stack:40,mode:"shipwrecked"},mysterymeat:{name:"Bile-Covered Slop",uncookable:!0,health:-1,hunger:-10,sanity:0,stack:20,
mode:"shipwrecked"},jellyfish:{name:"Jellyfish",fish:1,jellyfish:1,monster:1,perish:1.5*m,stack:40,mode:"shipwrecked"},jellyfish_dead:{name:"Dead Jellyfish",basename:"Jellyfish.",fish:1,jellyfish:1,monster:1,health:10,hunger:10,sanity:0,perish:g,stack:20,cook:"jellyfish_cooked",dry:"jellyfish_dried",drytime:v,mode:"shipwrecked"},jellyfish_cooked:{name:"Cooked Jellyfish",fish:1,jellyfish:1,monster:1,health:10,hunger:18.75,sanity:0,perish:f,stack:20,mode:"shipwrecked"},jellyfish_dried:{name:"Dried Jellyfish",
fish:1,jellyfish:1,monster:1,health:10,hunger:18.75,sanity:0,perish:C,stack:20,mode:"shipwrecked"},lobster:{name:"Wobster",fish:2,perish:2*v,mode:"shipwrecked"},lobster_dead:{name:"Dead Wobster",basename:"Wobster.",uncookable:!0,health:1,hunger:12.5,sanity:0,perish:p,stack:10,cook:"lobster_cooked",mode:"shipwrecked"},lobster_cooked:{name:"Delicious Wobster",uncookable:!0,health:1,hunger:12.5,sanity:0,perish:g,stack:40,mode:"shipwrecked"},crab:{name:"Crab",skip:!0,fish:.5,perish:2*v,cook:"fish_raw_small_cooked",
mode:"shipwrecked"},fish_raw_small:{name:"Fish Morsel",fish:.5,health:1,hunger:12.5,perish:p,sanity:0,stack:40,dry:"morsel_dried",drytime:v,mode:"shipwrecked"},fish_raw_small_cooked:{name:"Cooked Fish Morsel",fish:.5,health:1,hunger:12.5,sanity:0,perish:g,stack:40,mode:"shipwrecked"},tigereye:{name:"Eye of the Tiger Shark",uncookable:!0,health:60,hunger:75,sanity:-15,stack:10,mode:"shipwrecked"},dragoonheart:{name:"Dragoon Heart",uncookable:!0,health:11,hunger:25,sanity:-10,perish:f,stack:10,note:"Gives 90 seconds of light",
mode:"shipwrecked"},wormlight_lesser:{name:"Lesser Glowberry",uncookable:!0,health:3,hunger:12.5,sanity:-10,perish:p,stack:40,note:"Gives 22.5 seconds of light",mode:"together"},phlegm:{name:"Phlegm",uncookable:!0,health:0,hunger:12.5,sanity:-15,perish:p,stack:40,mode:"together"}},va=function(){return this.op+this.qty},wa={"=":function(a){return a===this.qty},">":function(a){return a>this.qty},"<":function(a){return a<this.qty},">=":function(a){return a>=this.qty},"<=":function(a){return a<=this.qty}},
da={test:function(a){return!!a},toString:function(){return""}},m=function(a,d){return{op:a,qty:d,test:wa[a],toString:va}},xa=function(a,d,b){return this.item1.test(a,d,b)&&this.item2.test(a,d,b)},ya=function(){return this.item1+" and "+this.item2},za=function(a,d,b){return this.item1.test(a,d,b)||this.item2.test(a,d,b)},Aa=function(){return this.item1+" or "+this.item2},G=function(a,d){return{item1:a,item2:d,test:za,toString:Aa,cancel:a.cancel||d.cancel}},Ba=function(a,d,b){return!this.item.test(a,
d,b)},Ca=function(){return this.item.toString().substring(0,this.item.toString().length-1)+"|strike]"},n=function(a){return{item:a,test:Ba,toString:Ca,cancel:!0}},Da=function(a,d,b){return(d[this.name]||0)+(d[this.name+"_cooked"]||0)},Ea=function(){return"[*"+q[this.name].name+"|"+q[this.name].img+" "+q[this.name].name+"]"+(q[this.name].cook?"[*"+q[this.name].cook.name+"|"+q[this.name].cook.img+"]":"")+(q[this.name].raw?"[*"+q[this.name].raw.name+"|"+q[this.name].raw.img+"]":"")+(this.qty?this.qty:
"")},D=function(a,d){return{name:a,qty:d||da,test:Da,toString:Ea}},Fa=function(a,d,b){return d[this.name]},Ga=function(){return"[*"+q[this.name].name+"|"+q[this.name].img+" "+q[this.name].name+"]"+(this.qty?this.qty:"")},r=function(a,d){return{name:a,qty:d||da,test:Fa,toString:Ga}},Ha=function(a,d,b){return b[this.tag]},Ia=function(){return"[tag:"+this.tag+"|"+this.tag+"]"+(this.qty?this.qty:"")},e=function(a,d){return{tag:a,qty:d||da,test:Ha,toString:Ia}},h={butterflymuffin:{name:"Butter Muffin",
test:function(a,d,b){return d.butterflywings&&!b.meat&&b.veggie},requires:"Butterfly Wings, veggie",requirements:[D("butterflywings"),n(e("meat")),e("veggie")],priority:1,weight:1,foodtype:"veggie",health:20,hunger:37.5,perish:u,sanity:5,cooktime:2},frogglebunwich:{name:"Froggle Bunwich",test:function(a,d,b){return(d.froglegs||d.froglegs_cooked)&&b.veggie},requirements:[D("froglegs"),e("veggie")],priority:1,foodtype:"meat",health:20,hunger:37.5,perish:u,sanity:5,cooktime:2},taffy:{name:"Taffy",test:function(a,
d,b){return b.sweetener&&3<=b.sweetener&&!b.meat},requirements:[e("sweetener",m(">=",3)),n(e("meat"))],priority:10,foodtype:"veggie",health:-3,hunger:25,perish:u,sanity:15,cooktime:2,tags:["honeyed"]},pumpkincookie:{name:"Pumpkin Cookie",test:function(a,d,b){return(d.pumpkin||d.pumpkin_cooked)&&b.sweetener&&2<=b.sweetener},requirements:[D("pumpkin"),e("sweetener",m(">=",2))],priority:10,foodtype:"veggie",health:0,hunger:37.5,perish:f,sanity:15,cooktime:2,tags:["honeyed"]},stuffedeggplant:{name:"Stuffed Eggplant",
test:function(a,d,b){return(d.eggplant||d.eggplant_cooked)&&b.veggie&&1<b.veggie},requirements:[D("eggplant"),e("veggie",m(">",1))],priority:1,foodtype:"veggie",health:3,hunger:37.5,perish:u,sanity:5,temperature:40,temperatureduration:5,cooktime:2},fishsticks:{name:"Fishsticks",test:function(a,d,b){return b.fish&&d.twigs&&b.inedible&&1>=b.inedible},requirements:[e("fish"),r("twigs"),e("inedible"),e("inedible",m("<=",1))],priority:10,foodtype:"meat",health:40,hunger:37.5,perish:f,sanity:5,cooktime:2},
honeynuggets:{name:"Honey Nuggets",test:function(a,d,b){return d.honey&&b.meat&&1.5>=b.meat&&!b.inedible},requirements:[r("honey"),e("meat",m("<=",1.5)),n(e("inedible"))],priority:2,foodtype:"meat",health:20,hunger:37.5,perish:u,sanity:5,cooktime:2,tags:["honeyed"]},honeyham:{name:"Honey Ham",test:function(a,d,b){return d.honey&&b.meat&&1.5<b.meat&&!b.inedible},requirements:[r("honey"),e("meat",m(">",1.5)),n(e("inedible"))],priority:2,foodtype:"meat",health:30,hunger:75,perish:u,sanity:5,temperature:40,
temperatureduration:10,cooktime:2,tags:["honeyed"]},dragonpie:{name:"Dragonpie",test:function(a,d,b){return(d.dragonfruit||d.dragonfruit_cooked)&&!b.meat},requirements:[D("dragonfruit"),n(e("meat"))],priority:1,foodtype:"veggie",health:40,hunger:75,perish:u,sanity:5,temperature:40,temperatureduration:10,cooktime:2},kabobs:{name:"Kabobs",test:function(a,d,b){return b.meat&&d.twigs&&(!b.monster||1>=b.monster)&&b.inedible&&1>=b.inedible},requirements:[e("meat"),r("twigs"),G(n(e("monster")),e("monster",
m("<=",1))),e("inedible"),e("inedible",m("<=",1))],priority:5,foodtype:"meat",health:3,hunger:37.5,perish:u,sanity:5,cooktime:2},mandrakesoup:{name:"Mandrake Soup",test:function(a,d,b){return d.mandrake},requirements:[r("mandrake")],priority:10,foodtype:"veggie",health:100,hunger:150,perish:g,sanity:5,cooktime:3},baconeggs:{name:"Bacon and Eggs",test:function(a,d,b){return b.egg&&1<b.egg&&b.meat&&1<b.meat&&!b.veggie},requirements:[e("egg",m(">",1)),e("meat",m(">",1)),n(e("veggie"))],priority:10,foodtype:"meat",
health:20,hunger:75,perish:C,sanity:5,cooktime:2},meatballs:{name:"Meatballs",test:function(a,d,b){return b.meat&&!b.inedible},requirements:[e("meat"),n(e("inedible"))],priority:-1,foodtype:"meat",health:3,hunger:62.5,perish:f,sanity:5,cooktime:.75},bonestew:{name:"Meaty Stew",test:function(a,d,b){return b.meat&&3<=b.meat&&!b.inedible},requirements:[e("meat",m(">=",3)),n(e("inedible"))],priority:0,foodtype:"meat",health:12,hunger:150,perish:f,sanity:5,temperature:40,temperatureduration:15,cooktime:.75},
perogies:{name:"Pierogi",test:function(a,d,b){return b.egg&&b.meat&&b.veggie&&!b.inedible},requirements:[e("egg"),e("meat"),e("veggie"),n(e("inedible"))],priority:5,foodtype:"meat",health:40,hunger:37.5,perish:C,sanity:5,temperature:40,temperatureduration:10,cooktime:1},turkeydinner:{name:"Turkey Dinner",test:function(a,d,b){return d.drumstick&&1<d.drumstick&&b.meat&&1<b.meat&&(b.veggie||b.fruit)},requirements:[r("drumstick",m(">",1)),e("meat",m(">",1)),G(e("veggie"),e("fruit"))],priority:10,foodtype:"meat",
health:20,hunger:75,perish:g,sanity:5,temperature:40,temperatureduration:10,cooktime:3},ratatouille:{name:"Ratatouille",test:function(a,d,b){return!b.meat&&b.veggie&&!b.inedible},requirements:[n(e("meat")),e("veggie"),n(e("inedible"))],priority:0,foodtype:"veggie",health:3,hunger:25,perish:u,sanity:5,temperature:-40,temperatureduration:5,cooktime:1},jammypreserves:{name:"Fist Full of Jam",test:function(a,d,b){return b.fruit&&!b.meat&&!b.veggie&&!b.inedible},requirements:[e("fruit"),n(e("meat")),n(e("veggie")),
n(e("inedible"))],priority:0,foodtype:"veggie",health:3,hunger:37.5,perish:u,sanity:5,cooktime:.5},fruitmedley:{name:"Fruit Medley",test:function(a,d,b){return b.fruit&&3<=b.fruit&&!b.meat&&!b.veggie},requirements:[e("fruit",m(">=",3)),n(e("meat")),n(e("veggie"))],priority:0,foodtype:"veggie",health:20,hunger:25,perish:g,sanity:5,temperature:-40,temperatureduration:5,cooktime:.5},fishtacos:{name:"Fish Tacos",test:function(a,d,b){return b.fish&&(d.corn||d.corn_cooked)},requirements:[e("fish"),D("corn")],
priority:10,foodtype:"meat",health:20,hunger:37.5,perish:g,sanity:5,cooktime:.5,tags:["monstermeat"]},waffles:{name:"Waffles",test:function(a,d,b){return d.butter&&(d.berries||d.berries_cooked)&&b.egg},requirements:[r("butter"),D("berries"),e("egg")],priority:10,foodtype:"veggie",health:60,hunger:37.5,perish:g,sanity:5,cooktime:.5},monsterlasagna:{name:"Monster Lasagna",test:function(a,d,b){return b.monster&&2<=b.monster&&!b.inedible},requirements:[e("monster",m(">=",2)),n(e("inedible"))],priority:10,
foodtype:"meat",health:-20,hunger:37.5,perish:g,sanity:-20,cooktime:.5},powcake:{name:"Powdercake",test:function(a,d,b){return d.twigs&&d.honey&&(d.corn||d.corn_cooked)},requirements:[r("twigs"),r("honey"),D("corn")],priority:10,foodtype:"veggie",health:-3,hunger:0,perish:9E6,sanity:0,cooktime:.5,tags:["honeyed"]},unagi:{name:"Unagi",test:function(a,d,b){return d.cutlichen&&(d.eel||d.eel_cooked)},requirements:[r("cutlichen"),D("eel")],priority:20,foodtype:"veggie",health:20,hunger:18.75,perish:f,
sanity:5,cooktime:.5},wetgoop:{name:"Wet Goop",test:function(a,d,b){return!0},requirements:[],trash:!0,priority:-2,health:0,hunger:0,perish:g,sanity:0,cooktime:.25},flowersalad:{name:"Flower Salad",test:function(a,d,b){return d.cactusflower&&b.veggie&&2<=b.veggie&&!b.meat&&!b.inedible&&!b.egg&&!b.sweetener&&!b.fruit},requirements:[r("cactusflower"),e("veggie",m(">=",2)),n(e("meat")),n(e("inedible")),n(e("egg")),n(e("sweetener")),n(e("fruit"))],priority:10,foodtype:"veggie",health:40,hunger:12.5,perish:g,
sanity:5,cooktime:.5,mode:"giants"},icecream:{name:"Ice Cream",test:function(a,d,b){return b.frozen&&b.dairy&&b.sweetener&&!b.meat&&!b.veggie&&!b.inedible&&!b.egg},requirements:[e("frozen"),e("dairy"),e("sweetener"),n(e("meat")),n(e("veggie")),n(e("inedible")),n(e("egg"))],priority:10,foodtype:"veggie",health:0,hunger:25,perish:p,sanity:50,temperature:-40,temperatureduration:15,cooktime:.5,mode:"giants"},watermelonicle:{name:"Melonsicle",test:function(a,d,b){return d.watermelon&&b.frozen&&d.twigs&&
!b.meat&&!b.veggie&&!b.egg},requirements:[r("watermelon"),e("frozen"),r("twigs"),n(e("meat")),n(e("veggie")),n(e("egg"))],priority:10,foodtype:"veggie",health:3,hunger:12.5,perish:p,sanity:20,temperature:-40,temperatureduration:10,cooktime:.5,mode:"giants"},trailmix:{name:"Trail Mix",test:function(a,d,b){return d.acorn_cooked&&b.seed&&1<=b.seed&&(d.berries||d.berries_cooked)&&b.fruit&&1<=b.fruit&&!b.meat&&!b.veggie&&!b.egg&&!b.dairy},requirements:[r("acorn_cooked"),e("seed",m(">=",1)),D("berries"),
e("fruit",m(">=",1)),n(e("meat")),n(e("veggie")),n(e("egg")),n(e("dairy"))],priority:10,foodtype:"veggie",health:30,hunger:12.5,perish:u,sanity:5,cooktime:.5,mode:"giants"},hotchili:{name:"Spicy Chili",test:function(a,d,b){return b.meat&&b.veggie&&1.5<=b.meat&&1.5<=b.veggie},requirements:[e("meat",m(">=",1.5)),e("veggie",m(">=",1.5))],priority:10,foodtype:"meat",health:20,hunger:37.5,perish:f,sanity:0,temperature:40,temperatureduration:15,cooktime:.5,mode:"giants"},guacamole:{name:"Guacamole",test:function(a,
d,b){return d.mole&&d.cactusmeat&&!b.fruit},requirements:[r("mole"),r("cactusmeat"),n(e("fruit"))],priority:10,foodtype:"meat",health:20,hunger:37.5,perish:f,sanity:0,cooktime:.5,mode:"giants"},californiaroll:{name:"California Roll",test:function(a,d,b){return d.seaweed&&2===d.seaweed&&b.fish&&1<=b.fish},requirements:[r("seaweed",m("=",2)),e("fish",m(">=",1))],priority:20,foodtype:"meat",health:20,hunger:37.5,perish:f,sanity:10,cooktime:.5,mode:"shipwrecked"},seafoodgumbo:{name:"Seafood Gumbo",test:function(a,
d,b){return b.fish&&2<b.fish},requirements:[e("fish",m(">",2))],priority:10,foodtype:"meat",health:40,hunger:37.5,perish:f,sanity:20,cooktime:1,mode:"shipwrecked"},bisque:{name:"Bisque",test:function(a,d,b){return d.limpets&&3===d.limpets&&b.frozen},requirements:[r("limpets",m("=",3)),e("frozen")],priority:30,foodtype:"meat",health:60,hunger:18.75,perish:f,sanity:5,cooktime:1,mode:"shipwrecked"},ceviche:{name:"Ceviche",test:function(a,d,b){return b.fish&&2<=b.fish&&b.frozen},requirements:[e("fish",
m(">=",2)),e("frozen")],priority:20,foodtype:"meat",health:20,hunger:25,perish:f,sanity:5,temperature:-40,temperatureduration:10,cooktime:.5,mode:"shipwrecked"},jellyopop:{name:"Jelly-O Pop",test:function(a,d,b){return b.jellyfish&&b.frozen&&b.inedible},requirements:[e("jellyfish"),e("frozen"),e("inedible")],priority:20,foodtype:"meat",health:20,hunger:12.5,perish:p,sanity:0,temperature:-40,temperatureduration:10,cooktime:.5,mode:"shipwrecked"},bananapop:{name:"Banana Pop",test:function(a,d,b){return d.cavebanana&&
b.frozen&&b.inedible&&!b.meat&&!b.fish},requirements:[r("cavebanana"),e("frozen"),e("inedible"),n(e("meat")),n(e("fish"))],priority:20,foodtype:"veggie",health:20,hunger:12.5,perish:p,sanity:33,temperature:-40,temperatureduration:10,cooktime:.5,mode:"shipwrecked"},lobsterbisque:{name:"Lobster Bisque",test:function(a,d,b){return d.lobster&&b.frozen},requirements:[r("lobster"),e("frozen")],priority:30,foodtype:"meat",health:60,hunger:25,perish:f,sanity:10,cooktime:.5,mode:"shipwrecked"},lobsterdinner:{name:"Lobster Dinner",
test:function(a,d,b){return d.lobster&&d.butter&&!b.meat&&!b.frozen},requirements:[r("lobster"),r("butter"),n(e("meat")),n(e("frozen"))],priority:25,foodtype:"meat",health:60,hunger:37.5,perish:u,sanity:50,cooktime:1,mode:"shipwrecked"},sharkfinsoup:{name:"Shark Fin Soup",test:function(a,d,b){return d.shark_fin},requirements:[r("shark_fin")],priority:20,foodtype:"meat",health:40,hunger:12.5,perish:f,sanity:-10,cooktime:1,note:"Gives 10 naughtiness",mode:"shipwrecked"},surfnturf:{name:"Surf 'n' Turf",
test:function(a,d,b){return b.meat&&2.5<=b.meat&&b.fish&&1.5<=b.fish&&!b.frozen},requirements:[e("meat",m(">=",2.5)),e("fish",m(">=",1.5)),n(e("frozen"))],priority:30,foodtype:"meat",health:60,hunger:37.5,perish:f,sanity:33,cooktime:1,mode:"shipwrecked"},coffee:{name:"Coffee",test:function(a,d,b){return d.coffeebeans_cooked&&(4===d.coffeebeans_cooked||3===d.coffeebeans_cooked&&(b.dairy||b.sweetener))},requirements:[G(r("coffeebeans_cooked",m("=",4)),function(a,d){return{item1:a,item2:d,test:xa,toString:ya,
cancel:a.cancel&&d.cancel}}(r("coffeebeans_cooked",m("=",3)),G(e("dairy"),e("sweetener"))))],priority:30,foodtype:"veggie",health:3,hunger:9.375,perish:f,sanity:-5,cooktime:.5,note:"Gives 5 bonus speed (+83%) for 0.5 days",mode:"shipwrecked"},sweetpotatosouffle:{name:"Sweet Potato Souffle",test:function(a,d,b){return d.sweet_potato&&2===d.sweet_potato&&b.egg&&2<=b.egg},requirements:[r("sweet_potato",m("=",2)),e("egg",m(">=",2))],priority:30,foodtype:"veggie",health:20,hunger:37.5,perish:f,sanity:15,
cooktime:2,mode:"warly"},monstertartare:{name:"Monster Tartare",test:function(a,d,b){return b.monster&&2<=b.monster&&b.egg&&b.veggie},requirements:[e("monster",m(">=",2)),e("egg"),e("veggie")],priority:30,foodtype:"meat",health:3,hunger:37.5,perish:f,sanity:10,cooktime:2,mode:"warly"},freshfruitcrepes:{name:"Fresh Fruit Crepes",test:function(a,d,b){return b.fruit&&1.5<=b.fruit&&d.butter&&d.honey},requirements:[e("fruit",m(">=",1.5)),r("butter"),r("honey")],priority:30,foodtype:"veggie",health:60,
hunger:150,perish:f,sanity:15,cooktime:2,mode:"warly"},musselbouillabaise:{name:"Mussel Bouillabaise",test:function(a,d,b){return d.mussel&&2===d.mussel&&b.veggie&&2<=b.veggie},requirements:[r("mussel",m("=",2)),e("veggie",m(">=",2))],priority:30,foodtype:"meat",health:20,hunger:37.5,perish:f,sanity:15,cooktime:2,mode:"warly"}},P=function(){var a,d,b=/^tag[: ]/,c=/^tag:? */,e=/^tagnot[: ]/,w=/^tagnot:? */,y,f=/^recipe[: ]/,g=/^recipe:? */,k,n=/^ingredient[: ]/,Ka=/^ingredient:? */,la,ma,m=!1,A=function(b){!m&&
b.uncookable||0===(b.modeMask&B)?b.match=0:0===b.lowerName.indexOf(a)||b.raw&&0===b.raw.lowerName.indexOf(a)?b.match=3:0===ma.test(b.lowerName)?b.match=2:la.test(b.lowerName)?b.match=1:b.match=0;return b.match},v=function(a){return a.match=a[d]+0||0},r=function(a){for(var b=0,d,c=!0;b<y.length;){d=y[b].test(null,a.nameObject,a);if(y[b].cancel){if(!d){c=!0;break}}else d&&(c=!1);b++}return a.match=c?0:1},t=function(a){for(var b=0,d,c=!0;b<a.requirements.length;){d=a.requirements[b].test(null,k.nameObject,
k);if(a.requirements[b].cancel){if(!d){c=!0;break}}else d&&(c=!1);b++}return a.match=c?0:1},p=function(b){return b.match=b.lowerName===a?1:0},E=function(b){return b.match=b.lowerName===a||b.raw&&b.raw.lowerName===a||b.cook&&b.cook.lowerName===a?1:0},u=function(a,b){var d,c;return a.match===b.match?(d=a.basename?a.basename:a.name,c=b.basename?b.basename:b.name,d!==c?d>c?1:d<c?-1:0:a.name===b.name?0:a.raw===b?1:-1):b.match-a.match};return function(l,I,Ja){m=!!Ja;a=I.toLowerCase();if(b.test(a))return d=
a.split(c)[1],l.filter(v).sort(u);if(e.test(a))return d=a.split(w)[1],l.filter(function(a){return!v(a)}).sort(u);if(f.test(a))return(y=h.byName(a.split(g)[1].toLowerCase()))?(y=y.requirements,l.filter(r).sort(u)):[];if(n.test(a))return(k=q.byName(a.split(Ka)[1].toLowerCase()))?l.filter(t).sort(u):[];if(0===a.indexOf("*"))return a=a.substring(1),l.filter(p).sort(u);if(0===a.indexOf("~"))return a=a.substring(1),l.filter(E).sort(u);ma=new RegExp("\\b"+a+".*");la=new RegExp("\\b"+a.split("").join(".*")+
".*");return l.filter(A).sort(u)}}(),ea=function(a,d,b){var c,e,w;for(c=0;c<a.length;c++)if(w=a[c],null!==w)for(e in d[w.id]=1+(d[w.id]||0),w)if(w.hasOwnProperty(e)&&"perish"!==e&&!isNaN(w[e])){var y=w[e];sa[e]?y*=F[w.preparationType]:ta[e]&&(y*=F[w[e+"Type"]]);b[e]=y+(b[e]||0)}else"perish"===e&&(b[e]=Math.min(b[e]||C,w[e]))},na=function(){var a,d;return function(b,c,e,w){var l,f;b.length=0;a={};d={};ea(c,a,d);d.hunger=d.bestHunger;d.health=d.bestHealth;d.sanity=d.bestSanity;c=0;a:for(;c<h.length;c++)if(f=
!1,0!==(h[c].modeMask&B)){for(l=0;l<h[c].requirements.length;l++)if(h[c].requirements[l].test(null,a,d))h[c].requirements[l].cancel||(f=!0);else if(!w&&h[c].requirements[l].cancel)continue a;else if(w&&!h[c].requirements[l].cancel)continue a;!f||e&&-1!==e.indexOf(h[c])||b.push(h[c])}d.img="";d.name="Combined";return b}}(),La=function(){var a=[],d,b;return function(c){a.length=0;d={};b={};ea(c,d,b);b.hunger=b.bestHunger;b.health=b.bestHealth;b.sanity=b.bestSanity;for(c=0;c<h.length;c++)h[c].test(null,
d,b)&&0!==(h[c].modeMask&B)&&a.push(h[c]);a.sort(function(a,b){return b.priority-a.priority});b.img="";b.name="Combined";b.priority=" ";b.perish=0;b.cooktime=0;a.unshift(b);return a}}(),O=function(){var a=document.createElement("canvas"),d=a.getContext&&a.toDataURL&&a.getContext("2d"),b=document.createElement("canvas"),c=b.getContext&&b.getContext("2d"),e={},f={},y=!!d,g=[],h=function(l){var w=function(l,w){d.clearRect(0,0,64,64);d.drawImage(w,0,0,64,64);c.clearRect(0,0,32,32);c.drawImage(w,0,0,32,
32);try{e[l]=a.toDataURL(),f[l]=b.toDataURL()}catch(A){y=!1}g.filter(function(a){return a.url===l}).forEach(function(a){a.url===l&&(delete a.img.dataset.pending,U&&a.img.removeAttribute("data-pending"),a.img.src=32===a.d?f[l]||l:e[l]||l)});g=g.filter(function(a){return a.url!==l})};return function(a){w(l,a.target)}},k=function(a,b,d){a.dataset.pending=b;U&&a.setAttribute("data-pending",b);g.push({url:b,img:a,d:d})},q=function(a,b){var d=new Image,c;y?e[a]?d.src=32===b?f[a]:e[a]:(null!==e[a]&&(e[a]=
null,c=new Image,c.addEventListener("load",h(a),!1),c.src=a),k(d,a,b)):d.src=a;return d};a.width=64;a.height=64;b.width=32;b.height=32;q.queue=k;return q}(),fa=function(){var a=/\[([^\|]*)\|([^\|\]]*)\|?([^\|\]]*)\]/,d=/([^\|]\]\[[^\|]+\|[^\|\]]+)\|?([^\|\](?:left)]*)(?=\])/g,b=/(\[[^\|]+\|[^\|\]]+)\|?([^\|\]]*)(?=\]\[)(?!\]\[\|)/g,c=function(a,b,d){return b+"|"+(0===d.length?"left":d+" left")},e=function(a,b,d){return b+"|"+(0===d.length?"right":d+" right")},f=/_(\w)/g,y=function(a,b){return" "+
b.toUpperCase()};return function(l){var w=l&&l.replace(d,c).replace(d,c).replace(b,e);l=w&&w.split(a);var g,h,k,I;if(l&&1!==l.length)for(w=document.createDocumentFragment(),w.appendChild(document.createTextNode(l[0])),g=1;g<l.length;g+=4)""===l[g]&&""===l[g+1]?w.appendChild(document.createElement("br")):(h=document.createElement("span"),h.className=""===l[g+2]?"link":"link "+l[g+2],h.dataset.link=l[g],U&&h.setAttribute("data-link",l[g]),l[g+1]&&0===l[g+1].indexOf("img/")?(h.appendChild(document.createTextNode(l[g+
1].split(" ").slice(1).join(" "))),k=l[g+1].split(" ")[0],I=O(k,32),I.title=(k.substr(4,1).toUpperCase()+k.substr(5).replace(f,y)).split(".")[0],h.appendChild(I)):h.appendChild(document.createTextNode(l[g+1]?l[g+1]:l[g])),w.appendChild(h)),w.appendChild(document.createTextNode(l[g+3]));return w}}(),k,p=0,oa=document.getElementById("main"),Ma=document.getElementById("food"),Na=document.getElementById("recipes"),ga=document.getElementById("navbar"),U=!1;document.documentElement.dataset||(U=!0,Object.defineProperty(Element.prototype,
"dataset",{get:function(){this.ds||(this.ds={},Array.prototype.forEach.call(this.attributes,function(a){0===a.name.indexOf("data-")&&(this.ds[a.name.substring(5)]=a.value)},this));return this.ds}}));document.getElementById("stalehealth").appendChild(document.createTextNode(Math.round(333)/10+"%"));document.getElementById("stalehunger").appendChild(document.createTextNode(Math.round(667)/10+"%"));document.getElementById("spoiledhunger").appendChild(document.createTextNode(Math.round(500)/10+"%"));
document.getElementById("spoiledsanity").appendChild(document.createTextNode(10));document.getElementById("perishground").appendChild(document.createTextNode(Math.round(1500)/10+"%"));document.getElementById("perishwinter").appendChild(document.createTextNode(Math.round(750)/10+"%"));document.getElementById("perishsummer").appendChild(document.createTextNode(Math.round(1250)/10+"%"));document.getElementById("perishfridge").appendChild(document.createTextNode(Math.round(500)/10+"%"));g=function(a,
d){return"[tag:"+a+"|"+(d||a)+"]"};for(k in q)if(q.hasOwnProperty(k)){var c=q[k];c.match=0;c.lowerName=c.name.toLowerCase();c.id=k;c.nameObject={};c.nameObject[k]=1;c.img="img/"+c.name.replace(/ /g,"_").replace(/'/g,"").toLowerCase()+".png";c.preparationType=c.preparationType||"raw";q[k+"_cooked"]&&(c.cook=q[k+"_cooked"]);"string"===typeof c.cook&&(c.cook=q[c.cook]);c.cook&&!c.cook.raw&&(c.cook.raw=c,c.cook.cooked=!0,c.cook.basename||(c.cook.basename=(c.basename||c.name)+"."));"string"===typeof c.raw&&
(c.raw=q[c.raw],c.cooked=!0,c.basename||(c.basename=(c.raw.basename||c.raw.name)+"."));"string"===typeof c.dry&&(c.dry=q[c.dry]);c.dry&&!c.dry.wet&&(c.dry.wet=c,c.dry.rackdried=!0,c.dry.basename||(c.dry.basename=(c.basename||c.name)+".."));"string"===typeof c.wet&&(c.rackdried=!0,c.wet=q[c.wet],c.basename||(c.basename=(c.wet.basename||c.wet.name)+".."));c.cook&&(c.cook.preparationType="cooked");c.dry&&(c.dry.preparationType="dried");for(k=0;k<H.length;k++)f=H[k],u=c[f]||0,m=c.preparationType,c.raw&&
(u=Math.max(c.raw[f]||0,u),u===c.raw[f]&&(m="raw")),c.cook&&(u=Math.max(c.cook[f]||0,u),u===c.cook[f]&&(m="cooked")),f=f.charAt(0).toUpperCase()+f.slice(1),c["best"+f]=u,c["best"+f+"Type"]=m;c.info=[];f=c.info;c.fruit&&f.push(g("fruit")+(1===c.fruit?"":"\u00d7"+c.fruit));c.veggie&&f.push(g("veggie","vegetable")+(1===c.veggie?"":"\u00d7"+c.veggie));c.meat&&f.push(g("meat")+(1===c.meat?"":"\u00d7"+c.meat));c.egg&&f.push(g("egg")+(1===c.egg?"":"\u00d7"+c.egg));c.fish&&f.push(g("fish")+(1===c.fish?"":
"\u00d7"+c.fish));c.magic&&f.push(g("magic"));c.decoration&&f.push(g("decoration"));c.inedible&&f.push(g("inedible"));c.monster&&f.push(g("monster","monster food"));c.sweetener&&f.push(g("sweetener"));c.fat&&f.push(g("fat"));c.dairy&&f.push(g("dairy"));c.comment&&f.push(c.comment);q[p++]=c}q.length=p;p=0;for(k in h)h.hasOwnProperty(k)&&(h[k].match=0,h[k].name=h[k].name||k,h[k].id=k,h[k].lowerName=h[k].name.toLowerCase(),h[k].weight=h[k].weight||1,h[k].priority=h[k].priority||0,h[k].img="img/"+h[k].name.replace(/ /g,
"_").replace(/'/g,"").toLowerCase()+".png",h[k].requirements&&(h[k].requires=fa(h[k].requirements.join("; ")+(h[k].mode?"; [tag:"+h[k].mode+"|img/"+x[h[k].mode].img+"]":""))),h[k].mode?h[k][h[k].mode]=!0:(h[k].vanilla=!0,h[k].mode="vanilla"),h[k].modeMask=x[h[k].mode].bit,h[k].temperature&&(h[k].note=h[k].note?h[k].note+"; ":"",h[k].note+="Provides "+h[k].temperature+" heat for "+h[k].temperatureduration+" seconds"),h[k].preparationType="recipe",h[p++]=h[k]);h.length=p;h.forEach=Array.prototype.forEach;
h.filter=Array.prototype.filter;h.sort=Array.prototype.sort;h.byName=function(a){for(var d=this.length;d--;)if(this[d].lowerName===a)return this[d]};var H=function(a,d){return a+"[recipe:"+d.name+"|"+d.img+"]"},ha=function(a,d,b){return 1===d?a:a+(b||"s")};for(k=0;k<q.length;k++)c=q[k],f=c.info,c.cooked&&f.push("from [*"+c.raw.name+"|"+c.raw.img+"]"),c.cook&&(c.cook instanceof Object||(c.cook=q[c.cook]),f.push("cook: [*"+c.cook.name+"|"+c.cook.img+"]")),c.dry&&(c.dry instanceof Object||(c.dry=q[c.dry]),
f.push("dry in "+c.drytime/v+" "+ha("day",c.drytime/v)+": [*"+c.dry.name+"|"+c.dry.img+"]")),c.mode?(c[c.mode]=!0,f.push("requires [tag:"+c.mode+"|img/"+x[c.mode].img+"]")):(c.vanilla=!0,c.mode="vanilla"),c.modeMask=x[c.mode].bit,c.info=f.join("; "),c.uncookable?c.info+=(c.info?"[|]":"")+"cannot be added to crock pot":(c.recipes=[],h.forEach(function(a){for(var d=!1,b=a.requirements,l=b.length;l--;)if(b[l].test(null,c.nameObject,c))b[l].cancel||d||(d=!0);else if(b[l].cancel){d=!1;break}d&&c.recipes.push(a)}),
0<c.recipes.length&&(c.ingredient=!0,c.info+=c.recipes.reduce(H,"[|][ingredient:"+c.name+"|Recipes] "))),c.note&&(c.info+="[|]"+c.note),c.info=fa(c.info);q.forEach=Array.prototype.forEach;q.filter=Array.prototype.filter;q.sort=Array.prototype.sort;q.byName=function(a){for(var d=this.length;d--;)if(this[d].lowerName===a)return this[d]};var Oa=function(a,d,b){var c=b||[0,0,0,0],e,f=0,y=0;return function(b){for(var l;b--&&1<=a;){d(c);c[0]++;for(l=0;c[l]>=a;)l++,c[l]++;e=4;for(f=0;e--;)c[e]>=a?c[e]=f:
c[e]>f&&(f=c[e]);if(4===l)return!1;y++}return!0}};S=M=void 0;M=h.filter(function(a){return!a.trash}).sort(function(a,d){return d.priority-a.priority});S=M.map(function(a){return a.test});M.map(function(a){return a.test.toString()});M.map(function(a){return a.priority});var Pa=function(a,d,b,c){var e=S.length,l=[],f=0,g,h=60,k=function(b){return a[b]},q=Oa(a.length,function(a){a=a.map(k);var b,d=null,c={},f={},g=null,y=!1,w=S,h=M;ea(a,c,f);f.hunger=f.bestHunger;f.health=f.bestHealth;f.sanity=f.bestSanity;
for(b=0;b<e&&(null===d||h[b].priority>=d);b++)w[b](null,c,f)&&(null!==g&&(y=!0,g.multiple=!0),g={recipe:h[b],ingredients:a,tags:{health:f.health,hunger:f.hunger},multiple:y},l.push(g),d=h[b].priority)}),m=function(){var a=!1,e=Date.now();for(q(h)?setTimeout(m,0):a=!0;f<l.length&&l[f];f++)d(l[f]);g!==Date.now()-e&&(g=Date.now()-e+1,h=38/g*h+1|0);b&&b();a&&c&&c()};m()},Q;(function(){var a=ga.getElementsByTagName("li"),d={},b={},c,e,f=function(a){Q(a.target.dataset.tab)},g;Q=function(a){e.className=
"";e=d[a];c.style.display="none";c=b[a];e.className="selected";c.style.display="block"};for(k=0;k<a.length;k++)g=a[k],g.dataset.tab&&(d[g.dataset.tab]=g,b[g.dataset.tab]=document.getElementById(g.dataset.tab),b[g.dataset.tab].style.display="none",g.addEventListener("selectstart",function(a){a.preventDefault()},!1),g.addEventListener("click",f,!1));e=d.simulator;c=b.simulator;window.localStorage&&localStorage.foodGuideState&&(a=JSON.parse(localStorage.foodGuideState),a.activeTab&&d[a.activeTab]&&(e=
d[a.activeTab],c=b[a.activeTab],B=a.modeMask||x.shipwrecked.mask));e.className="selected";c.style.display="block";window.addEventListener("beforeunload",function(){var a;window.localStorage&&(localStorage.foodGuideState||(localStorage.foodGuideState="{}"),a=JSON.parse(localStorage.foodGuideState),a.activeTab=e.dataset.tab,a.modeMask=B,localStorage.foodGuideState=JSON.stringify(a))})})();var Qa=function(a){a.dataset.pending&&O.queue(a,a.dataset.pending,32)},ia=function(a){var d,b,c,e=document.createElement("tr"),
f;for(d=1;d<arguments.length;d++)b=document.createElement(a),f=(c=arguments[d])&&c.indexOf?c:c.toString(),c instanceof DocumentFragment?(b.appendChild(c.cloneNode(!0)),Array.prototype.forEach.call(b.getElementsByTagName("img"),Qa)):0===f.indexOf("img/")?(c=O(f),b.appendChild(c)):b.appendChild(document.createTextNode(f)),e.appendChild(b);return e},V=function(a,d,b,c,e,f,g,h,k,q){var l,y,w,m=!1,n,I,v,u=function(a,d,c){q&&!(v<q)||h&&!h(a)||(d=b(a),g&&g(a,c)&&(d.className="highlighted",n||(n=d),I=d),
l.appendChild(d),v++)},t=function(b,c,g){var h,k;if(c||b&&""!==b.target.dataset.sort||w){h=c||b&&b.target.dataset.sort||w;e&&(k=d.shift());"name"===h?d.sort(function(a,b){var d=a.basename?a.basename:a.name,c=b.basename?b.basename:b.name;return d!==c?d>c?1:d<c?-1:0:a.name===b.name?0:a.raw===b?1:-1}):d.sort(function(a,b){var d=a[h],c=b[h];return isNaN(d)||isNaN(c)?isNaN(d)&&isNaN(c)?0:isNaN(d)?1:-1:c-d});if(c||b)w===h?m=!m:(w=h,m=!1);m&&d.reverse();e&&d.unshift(k)}b=document.createElement("tr");for(y in a)c=
document.createElement("th"),-1===y.indexOf(":")?c.appendChild(document.createTextNode(y)):(c.appendChild(document.createTextNode(y.split(":")[0])),c.title=y.split(":")[1]),a[y]&&(a[y]===w&&(c.style.background=m?"#555":"#ccc",c.style.color=m?"#ccc":"#555",c.style.borderRadius="4px"),c.style.cursor="pointer",c.dataset.sort=a[y],c.addEventListener("click",t,!1)),b.appendChild(c);c=l;l=document.createElement("table");l.appendChild(b);I=n=null;v=0;d.forEach(u);f&&(l.className="links",Array.prototype.forEach.call(l.getElementsByClassName("link"),
function(a){a.addEventListener("click",f,!1)}));c&&c.parentNode.replaceChild(l,c);g&&(n&&n.offsetTop+l.offsetTop+oa.offsetTop+n.offsetHeight>window.scrollY+window.innerHeight?n.scrollIntoView(!0):I&&I.offsetTop+l.offsetTop+oa.offsetTop<window.scrollY&&I.scrollIntoView(!1))};c?t(null,c):t();l.update=function(a){t(null,null,a)};l.setMaxRows=function(a){q=a;this.update()};return l},z=function(a){if(isNaN(a))return"";a=parseFloat(parseFloat(a).toFixed(4));return 0<a?"+"+a:a},pa=function(a,d){return a<
d?(d-a)/Math.abs(a):a>d?-(a-d)/Math.abs(a):0},ja=function(a,d){var b=isNaN(a)||a===d?"":" ("+z((100*(a<d?(d-a)/Math.abs(a):a>d?-(a-d)/Math.abs(a):0)).toFixed(0))+"%)";return-1===b.indexOf("Infinity")?b:" ("+z(d-a)+")"},qa=function(a){var d=F[a.preparationType],b=z(a.health*d),c=z(a.hunger*d),d=isNaN(a.sanity)?"":a.sanity*d;if(a.cook){var e=F[a.cook.preparationType];a.cook.health!==(a.health||0)&&(b+=" ("+z(a.cook.health*e-(b||0))+")");a.cook.hunger!==(a.hunger||0)&&(c+=" ("+z(a.cook.hunger*e-(c||
0))+")");a.cook.sanity!==(a.sanity||0)&&(d+=" ("+z(a.cook.sanity*e-(d||0))+")")}return ia("td",a.img?a.img:"",a.name,b,c,d,isNaN(a.perish)?"Never":a.perish/v+" "+ha("day",a.perish/v),a.info||"")},ca=function(a,d,b,c){var e=F[a.preparationType]||1,l=a.health*e,f=a.hunger*e,e=a.sanity*e;return ia("td",a.img?a.img:"",a.name,z(l)+ja(d,l),z(f)+ja(b,f),isNaN(e)?"":z(e)+ja(c,e),isNaN(a.perish)?"Never":a.perish/v+" "+ha("day",a.perish/v),(a.cooktime*ua+.5|0)+" secs",a.priority||"0",a.requires||"",a.note||
"")};(function(){var a,d=[],b=[],c=function(a){return 0!==(a.modeMask&B)},e=V({"":"",Name:"name",Health:"health",Hunger:"hunger",Sanity:"sanity","Perish:Time to turn to rot":"perish",Info:""},Array.prototype.slice.call(q),qa,"name",!1,function(c){c=c.target?"IMG"===c.target.tagName?c.target.parentNode.dataset.link:c.target.dataset.link:c;"recipe:"===c.substring(0,7)||"ingredient:"===c.substring(0,11)?(Q("crockpot"),"recipe:"===c.substring(0,7)&&(c="*"+c.substring(7)),b=P(h,c),f.update(!0)):(a!==c?
(a=c,d=P(q,c)):(a="",d.length=0),e.update(!0))},function(a){return-1!==d.indexOf(a)},c),f=V({"":"",Name:"name",Health:"health",Hunger:"hunger",Sanity:"sanity","Perish:Time to turn to rot":"perish","Cook Time":"cooktime","Priority:One of the highest priority recipes for a combination will be made":"priority","Requires:Dim, struck items cannot be used":"",Notes:""},Array.prototype.slice.call(h),ca,"name",!1,function(c){c=c.target?"IMG"===c.target.tagName?c.target.parentNode.dataset.link:c.target.dataset.link:
c;var l=c.substring(c.indexOf(":")+1);x[l]?(b=P(h,c),f.update(!0)):(Q("foodlist"),a=c,d=P(q,c),e.update(!0))},function(a){return-1!==b.indexOf(a)},c);Ma.appendChild(e);Na.appendChild(f);Y.push(function(){e.update();f.update()})})();var Ra=function(a,d){return a+"[ingredient:"+q[d.id].name+"|"+q[d.id].img+"]"},ra=function(a){var d=document.createElement("button");d.appendChild(document.createTextNode("Calculate efficient recipes (may take some time)"));d.className="makablebutton";d.addEventListener("click",
function(){var b=[],c=a?a.length:null,e,f,g=[],k,m,n,v,u,r=[],p=[],Z,A,x,B=function(a){return-1!==p.indexOf(a.id)},t=function(a){return-1!==this.indexOf(q[a])},D=function(a){-1!==p.indexOf(a.target.dataset.id)&&p.splice(p.indexOf(a.target.dataset.id),1);-1!==r.indexOf(a.target.dataset.id)?(r.splice(r.indexOf(a.target.dataset.id),1),a.target.className=""):(r.push(a.target.dataset.id),a.target.className="selected");x.update()},E=function(a){-1!==r.indexOf(a.target.dataset.id)&&r.splice(r.indexOf(a.target.dataset.id),
1);-1!==p.indexOf(a.target.dataset.id)?(p.splice(p.indexOf(a.target.dataset.id),1),a.target.className=""):(p.push(a.target.dataset.id),a.target.className="excluded");x.update();a.preventDefault()},aa=[],J=[],C=function(a){f&&(f.className="");for(var b=0;b<J.length;b++)J[b].className="";aa.length=0;J.length=0;e===a.target.dataset.recipe?e=f=null:(e=a.target.dataset.recipe,f=a.target,a.target.className="selected");x.update()},K=function(a){f&&(f.className="",e=f=null);var b=J.indexOf(a.target);-1!==
b?(aa.splice(b,1),J.splice(b,1),a.target.className=""):(aa.push(a.target.dataset.recipe),J.push(a.target),a.target.className="excluded");x.update();a.preventDefault()};null===c&&(c=q.length,a=q);for(;c--;)a[c].skip?!a[c].cook||a[c].cook.uncookable||a[c].cook.skip||-1!==b.indexOf(a[c].cook)?!a[c].dry||a[c].dry.uncookable||a[c].dry.skip||-1!==b.indexOf(a[c].dry)||b.push(a[c].dry):b.push(a[c].cook):a[c].uncookable||a[c].cooked&&!a[c].ideal||a[c].rackdried&&!a[c].ideal||-1!==b.indexOf(a[c])||b.push(a[c]),
!a[c].cooked||a[c].raw.uncookable||a[c].raw.skip||-1!==b.indexOf(a[c].raw)||b.push(a[c].raw),!a[c].rackdried||a[c].wet.uncookable||a[c].wet.skip||-1!==b.indexOf(a[c].wet)||b.push(a[c].wet);Z=[];x=V({"":"",Name:"name",Health:"health","Health+:Health gained compared to ingredients":"healthpls",Hunger:"hunger","Hunger+:Hunger gained compared to ingredients":"hungerpls",Ingredients:""},Z,function(a){var b=a.recipe;return ia("td",b.img?b.img:"",b.name,z(b.health),z(a.healthpls)+" ("+z(100*a.healthpct|
0)+"%)",z(b.hunger),z(a.hungerpls)+" ("+z(100*a.hungerpct|0)+"%)",fa(a.ingredients.reduce(Ra,"")+(a.multiple?"*":"")))},"hungerpls",!1,null,null,function(a){return(!e||a.recipe.name===e)&&(0===aa.length||-1===aa.indexOf(a.recipe.name))&&(!p.length||!a.ingredients.some(B))&&(!r.length||r.every(t,a.ingredients))},0,15);A=document.createElement("div");m=document.createElement("div");m.appendChild(document.createTextNode("Computing combinations.."));c=document.createElement("div");c.appendChild(document.createTextNode("* combination has multiple possible results"));
A.appendChild(m);k=document.createElement("div");k.className="recipeFilter";A.appendChild(k);n=document.createElement("div");n.className="foodFilter";b.forEach(function(a){var b=O(a.img,32);b.dataset.id=a.id;b.addEventListener("click",D,!1);b.addEventListener("contextmenu",E,!1);b.title=a.name;n.appendChild(b)});A.appendChild(n);v=document.createElement("div");u=document.createElement("input");u.type="text";u.placeholder="use custom filter";u.className="customFilterInput";v.appendChild(u);A.appendChild(x);
d.parentNode.replaceChild(A,d);A.appendChild(c);Pa(b,function(a){var b,c;if(-1===g.indexOf(a.recipe.name)){for(b=0;b<g.length&&!(a.recipe.name<g[b]);b++);g.splice(b,0,a.recipe.name);c=O(h.byName(g[b].toLowerCase()).img);c.dataset.recipe=g[b];c.addEventListener("click",C,!1);c.addEventListener("contextmenu",K,!1);c.title=a.recipe.name;b<k.childNodes.length?k.insertBefore(c,k.childNodes[b]):k.appendChild(c)}a.name||(a.name=a.recipe.name,a.health=a.recipe.health,a.ihealth=a.tags.health,a.healthpls=a.recipe.health-
a.ihealth,a.hunger=a.recipe.hunger,a.ihunger=a.tags.hunger,a.hungerpls=a.recipe.hunger-a.ihunger,a.healthpct=pa(a.ihealth,a.recipe.health),a.hungerpct=pa(a.ihunger,a.recipe.hunger),a.sanity=a.recipe.sanity,a.perish=a.recipe.perish);Z.push(a)},function(){m.firstChild.textContent="Found "+Z.length+" valid recipes.. (you can change Food Guide tabs during this process)"},function(){x.setMaxRows(30);m.firstChild.textContent="Found "+Z.length+" valid recipes. Showing top 30 for selected recipe using all selected ingredients. Right-click to exclude recipes or ingredients."})},
!1);return d};document.getElementById("statistics").appendChild(ra());var Sa=function(a,c){return a.reduce(function(a,d){return Math.max(a,d[c]||0)},-1E5)};window.food=q;window.recipes=h;window.matchingNames=P;var X=function(a,c){if(null!==c)a.dataset.id=c.id;else{if(a.nextSibling&&null!==R(a.nextSibling)){X(a,R(a.nextSibling));X(a.nextSibling,null);return}a.dataset.id=null}null!==c?a.firstChild?a.replaceChild(O(c.img),a.firstChild):a.appendChild(O(c.img)):a.firstChild&&a.removeChild(a.firstChild);
a.title=c?c.name:""},R=function(a){return a&&(q[a.dataset.id]||h[a.dataset.id]||null)};(function(){for(var a=document.getElementsByClassName("ingredientpicker"),c=a.length;c--;)(function(){var b=document.createElement("span"),d,e=document.createElement("div"),f=document.createElement("ul"),g=a[c],k=c,m,n="recipes"===g.dataset.type?h:q,v=!g.dataset.cookable,r=g.nextSibling,p=r.getElementsByClassName("ingredient"),u,x=[],A,z=[],B=[],t=null,D=!1,E=document.getElementById("results"),C=document.getElementById("discoverfood"),
J=document.getElementById("discover"),F=document.getElementById("makable"),K=document.createElement("span"),G=function(a,b){for(var c=a;c.previousSibling;)if(c=c.previousSibling,b(c))return c;return null},M=function(a,b){for(var c=a;c.nextSibling;)if(c=c.nextSibling,b(c))return c;return null},H=!1,N=function(a){var b=q[a]||h[a]||null;if(u){for(a=0;a<p.length;a++)if(null===R(p[a]))return X(p[a],b),D&&A(),a;return-1}-1===p.indexOf(a)&&(p.push(a),a=document.createElement("span"),a.className="ingredient",
X(a,b),a.addEventListener("click",Q,!1),r.appendChild(a),D&&A());return 1},S=function(a){-1!==N(("IMG"===a.target.tagName?a.target.parentNode:a.target).dataset.id)&&a&&a.preventDefault&&a.preventDefault()},T=function(a){var b=O(a.img,32),c=document.createElement("span");c.appendChild(b);c.appendChild(document.createTextNode(a.name));c.dataset.id=a.id;-1!==x.indexOf(a)&&(c.style.opacity=.5);c.addEventListener("mousedown",S,!1);this.appendChild(c);this.dataset.length++},U=function(a){-1!==x.indexOf(q[a.dataset.id])?
a.style.opacity||(a.style.opacity=.5):a.style.opacity&&a.style.removeProperty("opacity")},Q=function(a){var b="IMG"===a.target.tagName?a.target.parentNode:a.target;if(u){if(null!==R(b))return X(b,null),A(),b.dataset.id}else return a=p.indexOf(b.dataset.id),p.splice(a,1),r.removeChild(b),A(),p[a]||null},ba=function(){var a;d.splitTag();a=P(n,d.getSearch(),v);e.removeChild(f);f=document.createElement("div");f.dataset.length=0;a.forEach(T,f);e.appendChild(f);t=null},W=function(a){a="IMG"===a.target.tagName?
a.target.parentNode.dataset.link:a.target.dataset.link;var b=P(n,a,v);1===b.length?N(b[0].id):(g.value=a,ba())},L;"ingredients"===r.id?A=function(){var a,b,c,d,e;x=Array.prototype.map.call(p,function(a){return R(a)});a=La(x);b=a[0].health;c=a[0].hunger;d=a[0].sanity;e=V({"":"",Name:"name",Health:"health",Hunger:"hunger",Sanity:"sanity","Perish:Time to turn to rot":"perish","Cook Time":"cooktime","Priority:One of the highest priority recipes for a combination will be made":"priority","Requires:Dim, struck items cannot be used":"",
Notes:""},a,function(a){return ca(a,b,c,d)},"priority",!0,W,function(a,b){return 0<b.length&&a.priority===Sa(b,"priority")});E.firstChild&&E.removeChild(E.firstChild);E.firstChild&&(E.removeChild(E.firstChild),E.removeChild(E.firstChild));E.appendChild(e);null!==x[0]&&(na(z,x,a),0<z.length&&(E.appendChild(document.createTextNode("Add more ingredients to make:")),e=V({"":"",Name:"name","Health:(% more than ingredients)":"health","Hunger:(% more than ingredients)":"hunger",Sanity:"sanity","Perish:Time to turn to rot":"perish",
"Cook Time":"cooktime","Priority:One of the highest priority recipes for a combination will be made":"priority","Requires:Dim, struck items cannot be used":"",Notes:""},z,function(a){return ca(a,b,c,d)},"priority",!1,W),E.appendChild(e)));f&&f.firstChild&&Array.prototype.forEach.call(f.getElementsByTagName("span"),U)}:"inventory"===r.id&&(A=function(){var a;x=Array.prototype.map.call(r.getElementsByClassName("ingredient"),function(a){return R(a)});C.firstChild&&C.removeChild(C.firstChild);J.firstChild&&
J.removeChild(J.firstChild);F.firstChild&&F.removeChild(F.firstChild);0<x.length&&(a=V({"":"",Name:"name",Health:"health",Hunger:"hunger",Sanity:"sanity","Perish:Time to turn to rot":"perish",Info:""},x,qa,"name"),C.appendChild(a),na(B,x,null,!0),0<B.length&&(a=V({"":"",Name:"name",Health:"health",Hunger:"hunger",Sanity:"sanity","Perish:Time to turn to rot":"perish","Cook Time":"cooktime","Priority:One of the highest priority recipes for a combination will be made":"priority","Requires:Dim, struck items cannot be used":"",
Notes:""},B,ca,"name"),J.appendChild(a),F.appendChild(ra(x))));f&&f.firstChild&&Array.prototype.forEach.call(f.getElementsByTagName("span"),U)});0!==p.length?(u=!0,Array.prototype.forEach.call(p,function(a){X(a,null);a.addEventListener("click",Q,!1)})):(p=[],u=!1);window.localStorage&&localStorage.foodGuideState&&(m=JSON.parse(localStorage.foodGuideState).pickers)&&m[k]&&m[k].forEach(function(a){q[a]&&N(a)});D=!0;b.className="searchselector retracted";b.appendChild(document.createTextNode("name"));
d=function(){var a=document.createElement("div"),c=!1,d=null,e=[{title:"name",prefix:"",placeholder:"Filter ingredients"},{title:"tag",prefix:"tag:",placeholder:"Meat, veggie, fruit, egg, monster..."},{title:"recipe",prefix:"recipe:",placeholder:"Find ingredients used in a recipe"}],f=e[0],h=null,k=function(){c=!1;a.style.height="0px";b.style.borderBottomLeftRadius="3px";a.style.borderTopLeftRadius="3px";null!==h&&(clearTimeout(h),h=null);b.className="searchselector retracted"},l=function(a){f=a;
g.placeholder=f.placeholder;b.firstChild.textContent=f.title},m=function(a){l(e[a.target.dataset.typeIndex]);ba();k()},n=/: */;b.addEventListener("click",function(){c?k():(null===d&&(a.style.height="auto",a.style.left=b.offsetLeft,a.style.top=b.offsetTop+b.offsetHeight,d=a.offsetHeight+"px",a.style.height="0px"),c=!0,a.style.height=d,b.style.borderBottomLeftRadius="0px",a.style.borderTopLeftRadius="0px",a.style.width="auto",a.style.width=Math.max(a.offsetWidth,b.offsetWidth+1)+"px",null!==h&&(clearTimeout(h),
h=null),b.className="searchselector extended")},!1);b.addEventListener("selectstart",function(a){a.preventDefault()},!1);b.addEventListener("mouseout",function(){null!==h&&clearTimeout(h);h=setTimeout(k,500)},!1);b.addEventListener("mouseover",function(){null!==h&&(clearTimeout(h),h=null)},!1);a.addEventListener("mouseout",function(){null!==h&&clearTimeout(h);h=setTimeout(k,500)},!1);a.addEventListener("mouseover",function(){null!==h&&(clearTimeout(h),h=null)},!1);e.forEach(function(b,c){var d=document.createElement("div");
d.appendChild(document.createTextNode(b.title));d.dataset.typeIndex=c;d.addEventListener("click",m,!1);b.element=d;a.appendChild(d)});g.parentNode.insertBefore(b,g);a.className="searchdropdown";g.parentNode.insertBefore(a,g);return{getTag:function(){return f.title},setSearchType:function(a){l(e[a])},getSearch:function(){return f.prefix+g.value},splitTag:function(){var a;a=g.value.split(n);var b,c;if(2===a.length)for(b=a[0].toLowerCase()+":",c=a[1],a=0;a<e.length;a++)if(b===e[a].prefix){l(e[a]);g.value=
c;break}}}}();e.className="ingredientdropdown";e.appendChild(f);e.addEventListener("mousedown",function(a){a.preventDefault()},!1);(function(){var a=P(n,d.getSearch(),v);e.removeChild(f);f=document.createElement("div");f.dataset.length=0;a.forEach(T,f);e.appendChild(f)})();K.className="clearingredients";K.appendChild(document.createTextNode("clear"));K.addEventListener("click",function(){if(""===g.value&&"name"===d.getTag())for(;R(r.firstChild);)Q({target:r.firstChild});else g.value="",d.setSearchType(0),
ba()},!1);K.addEventListener("mouseover",function(){""===g.value&&"name"===d.getTag()&&(K.firstChild.textContent="clear chosen ingredients")},!1);K.addEventListener("mouseout",function(){"clear"!==K.firstChild.textContent&&(K.firstChild.textContent="clear")},!1);r.parentNode.insertBefore(K,r);r.parentNode.insertBefore(e,r);g.addEventListener("keydown",function(a){var b;-1!==[16,17,37,38,39,40,13].indexOf(a.keyCode)&&(b=t,13===a.keyCode?(null===t&&(t=f.firstChild||null),null!==t&&S({target:t})):null===
t?40===a.keyCode&&(t=f.childNodes[1]||f.firstChild||null,null!==t&&(L=t.offsetLeft+t.offsetWidth/2,a.preventDefault())):(a.preventDefault(),37===a.keyCode?(t=t.previousSibling&&t.previousSibling.offsetTop===t.offsetTop?t.previousSibling:(a=M(t,function(a){return a.offsetTop!==t.offsetTop}))?a.previousSibling:f.lastChild,null!==t&&(L=t.offsetLeft+t.offsetWidth/2)):39===a.keyCode?(t=t.nextSibling&&t.nextSibling.offsetTop===t.offsetTop?t.nextSibling:(a=G(t,function(a){return a.offsetTop!==t.offsetTop}))?
a.nextSibling:f.firstChild,null!==t&&(L=t.offsetLeft+t.offsetWidth/2)):38===a.keyCode?((a=G(t,function(a){return L>=a.offsetLeft-1&&L<=a.offsetLeft+a.offsetWidth+1}))||(a=G(f.lastChild,function(a){return L>=a.offsetLeft-1&&L<=a.offsetLeft+a.offsetWidth+1})),t=a?a:f.firstChild):40===a.keyCode&&((a=M(t,function(a){return L>=a.offsetLeft-1&&L<=a.offsetLeft+a.offsetWidth+1}))||(a=M(f.firstChild,function(a){return L>=a.offsetLeft-1&&L<=a.offsetLeft+a.offsetWidth+1})),t=a?a:f.lastChild)),t!==b&&(null!==
b&&(b.className=""),null!==t&&(t.className="selected")))},!1);g.addEventListener("keyup",function(a){-1===[16,17,37,38,39,40,13].indexOf(a.keyCode)?ba():null!==t&&a.preventDefault()},!1);g.addEventListener("focus",function(){H||(H=!0)},!1);g.addEventListener("blur",function(){H&&(H=!1)},!1);A();window.addEventListener("beforeunload",function(){var a,b;window.localStorage&&(localStorage.foodGuideState||(localStorage.foodGuideState="{}"),a=JSON.parse(localStorage.foodGuideState),a.pickers||(a.pickers=
[]),u?(b=[],b=Array.prototype.map.call(p,function(a){return(a=R(a))?a.id:null}),a.pickers[k]=b):a.pickers[k]=p,localStorage.foodGuideState=JSON.stringify(a))});Y.push(ba);Y.push(A)})()})();var H=function(a){W(x[a.target.dataset.mode].mask)},p=function(a){W(B^x[a.target.dataset.mode].bit);a.preventDefault()},N=document.createElement("li");ga.insertBefore(N,ga.firstChild);N.className="mode";for(var ka in x)g=O("img/"+x[ka].img),g.dataset.mode=ka,g.addEventListener("click",H,!1),g.addEventListener("contextmenu",
p,!1),g.title=x[ka].name+"\nleft-click to select\nright-click to toggle",N.appendChild(g);W(B)})();
