/*
Makes use of no third-party code (for better or worse)

Copyright (c) 2014

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

(function(){var J,q=480,H=["hunger","health","sanity"],ua={hunger:!0,health:!0,sanity:!0},va={bestHunger:!0,bestHealth:!0,bestSanity:!0},n=1*q,u=3*q,f=6*q,g=10*q,r=15*q,E=20*q,G=40*q,m=2*q,wa=q/16*.6666,Q={raw:1,dried:1,cooked:1,recipe:1},A=Q,aa=[],B=7,x={vanilla:{name:"Vanilla",img:"vanilla.png",bit:1,mask:1,color:"#ff592e"},giants:{name:"Reign of Giants",img:"reign_of_giants.png",bit:2,mask:3,color:"#b857c6"},shipwrecked:{name:"Shipwrecked",img:"shipwrecked.png",bit:4,mask:7,color:"#50c1cc"},together:{name:"Don't Starve Together",
img:"together.png",bit:8,mask:11,color:"#c0c0c0"},warly:{name:"Warly",img:"warly.png",bit:16,mask:23,multipliers:{raw:.7,dried:.8,cooked:.9,recipe:1.2}}},R=function(a){A={};for(d in Q)Q.hasOwnProperty(d)&&(A[d]=Q[d]);B=a;for(var d=0;d<L.childNodes.length;d++){a=L.childNodes[d];var b=x[a.dataset.mode];a.className=0!==(B&b.bit)?"enabled":"";if(b.multipliers&&0!==(B&b.bit))for(var c in b.multipliers)b.multipliers.hasOwnProperty(c)&&(A[c]*=b.multipliers[c])}for(d=0;d<aa.length;d++)aa[d]();c=["together",
"shipwrecked","giants","vanilla"];for(d=0;d<c.length;d++)if(0!==(B&x[c[d]].bit)){document.getElementsByTagName("BODY")[0].style["background-color"]=x[c[d]].color;break}},p={acorn:{name:"Birchnut",uncookable:!0,perish:E,stack:40,mode:"giants"},acorn_cooked:{name:"Roasted Birchnut",ideal:!0,seed:1,hunger:9.375,health:1,sanity:0,perish:f,stack:40,mode:"giants"},butter:{name:"Butter",fat:1,dairy:1,health:40,hunger:25,sanity:0,perish:G,stack:40},butterflywings:{name:"Butterfly Wings",isveggie:!0,decoration:2,
health:8,hunger:9.375,sanity:0,perish:f,stack:40},cactusflower:{name:"Cactus Flower",veggie:.5,hunger:12.5,health:8,sanity:5,perish:u,stack:40,mode:"giants"},deerclopseyeball:{name:"Deerclops Eyeball",uncookable:!0,health:60,hunger:75,sanity:-15},bird_egg:{name:"Egg",egg:1,health:0,hunger:9.375,sanity:0,perish:g,stack:40,rot:"rottenegg"},bird_egg_cooked:{name:"Cooked Egg",egg:1,precook:1,health:0,hunger:12.5,sanity:0,perish:f,stack:40},rottenegg:{name:"Rotten Egg",uncookable:!0,health:-1,hunger:-10,
sanity:0,stack:40},cutlichen:{name:"Lichen",isveggie:!0,veggie:1,health:3,hunger:12.5,sanity:-5,perish:2*q},eel:{name:"Eel",ismeat:!0,meat:.5,fish:1,health:3,hunger:9.375,sanity:0,perish:u,stack:40,dry:"morsel_dried",drytime:q},eel_cooked:{name:"Cooked Eel",ismeat:!0,health:8,hunger:12.5,sanity:0,perish:f,stack:40},fish:{name:"Fish",ismeat:!0,meat:.5,fish:1,health:1,hunger:12.5,sanity:0,perish:u,stack:40,drytime:q,dry:"morsel_dried"},fish_cooked:{name:"Cooked Fish",ismeat:!0,meat:.5,fish:1,precook:1,
health:1,hunger:12.5,sanity:0,perish:f,stack:40},froglegs:{name:"Frog Legs",ismeat:!0,meat:.5,health:0,hunger:12.5,perish:f,sanity:-10,stack:40},froglegs_cooked:{name:"Cooked Frog Legs",ismeat:!0,meat:.5,precook:1,health:1,hunger:12.5,perish:g,sanity:0,stack:40},foliage:{name:"Foliage",uncookable:!0,health:1,hunger:0,sanity:0,perish:f,stack:40},goatmilk:{name:"Electric Milk",dairy:1,health:3,hunger:12.5,sanity:10,perish:f,stack:40,mode:"giants"},honey:{name:"Honey",sweetener:!0,health:3,hunger:9.375,
sanity:0,perish:G,stack:40},honeycomb:{name:"Honeycomb",sweetener:!0},ice:{name:"Ice",frozen:1,health:.5,hunger:2.34375,sanity:0,perish:u,stack:40,mode:"giants"},lightbulb:{name:"Light Bulb",health:1,hunger:0,sanity:0,perish:f,stack:40,uncookable:!0},mandrake:{name:"Mandrake",veggie:1,magic:1,health:60,hunger:75,sanity:0,stack:40},mandrake_cooked:{name:"Cooked Mandrake",uncookable:!0,veggie:1,magic:1,precook:1,health:100,hunger:150,sanity:0,stack:40},mole:{name:"Moleworm",ideal:!0,meat:.5,perish:2*
q,cook:"morsel_cooked",mode:"giants"},plantmeat:{name:"Leafy Meat",uncookable:!0,health:0,hunger:12.5,sanity:-10,perish:f,stack:40},plantmeat_cooked:{name:"Cooked Leafy Meat",uncookable:!0,health:1,hunger:18.75,sanity:0,perish:g,stack:40},monstermeat:{name:"Monster Meat",ismeat:!0,meat:1,monster:!0,health:-20,hunger:18.75,sanity:-15,perish:f,stack:20,dry:"monstermeat_dried",drytime:q},monstermeat_cooked:{name:"Cooked Monster Meat",ismeat:!0,meat:1,monster:!0,precook:1,health:-3,hunger:18.75,sanity:-10,
perish:r,stack:20},monstermeat_dried:{name:"Monster Jerky",ismeat:!0,meat:1,monster:!0,dried:1,health:-3,hunger:18.75,sanity:-5,perish:E,stack:20},meat:{name:"Meat",ismeat:!0,meat:1,health:1,hunger:25,sanity:-10,perish:f,stack:20,dry:"meat_dried",drytime:m},meat_cooked:{name:"Cooked Meat",ismeat:!0,meat:1,precook:1,health:3,hunger:25,sanity:0,perish:g,stack:20},meat_dried:{name:"Jerky",ismeat:!0,meat:1,dried:1,health:20,hunger:25,sanity:15,perish:E,stack:20},morsel:{name:"Morsel",ismeat:!0,meat:.5,
health:0,hunger:12.5,sanity:-10,perish:f,stack:40,drytime:q,dry:"morsel_dried"},morsel_cooked:{name:"Cooked Morsel",raw:"morsel",ismeat:!0,meat:.5,precook:1,health:1,hunger:12.5,sanity:0,perish:g,stack:40},morsel_dried:{name:"Small Jerky",wet:"morsel",ismeat:!0,meat:.5,dried:1,health:8,hunger:12.5,sanity:10,perish:E,stack:40},drumstick:{name:"Drumstick",ismeat:!0,ideal:!0,meat:.5,health:0,hunger:12.5,sanity:-10,perish:f,stack:20,drytime:q,dry:"morsel_dried"},drumstick_cooked:{name:"Fried Drumstick",
ismeat:!0,meat:.5,precook:1,health:1,hunger:12.5,sanity:0,perish:g,stack:20},batwing:{name:"Batilisk Wing",ismeat:!0,health:3,hunger:12.5,sanity:-10,perish:f,stack:40,drytime:m,dry:"morsel_dried",uncookable:!0},batwing_cooked:{name:"Cooked Batilisk Wing",ismeat:!0,health:8,hunger:18.75,sanity:0,perish:g,uncookable:!0},minotaurhorn:{name:"Guardian's Horn",uncookable:!0,ismeat:!0,health:60,hunger:75,sanity:-15},red_mushroom:{name:"Red Cap",basename:"CapRed",veggie:.5,ideal:!0,health:-20,hunger:12.5,
sanity:0,perish:g,stack:40},red_mushroom_cooked:{name:"Cooked Red Cap",veggie:.5,health:1,hunger:0,sanity:-10,perish:g,stack:40},green_mushroom:{name:"Green Cap",basename:"CapGreen",veggie:.5,ideal:!0,health:0,hunger:12.5,sanity:-50,perish:g,stack:40},green_mushroom_cooked:{name:"Cooked Green Cap",veggie:.5,health:-1,hunger:0,sanity:15,perish:g,stack:40},blue_mushroom:{name:"Blue Cap",basename:"CapBlue",veggie:.5,ideal:!0,health:20,hunger:12.5,sanity:-15,perish:g,stack:40},blue_mushroom_cooked:{name:"Cooked Blue Cap",
veggie:.5,health:-3,hunger:0,sanity:10,perish:g,stack:40},petals:{name:"Petals",uncookable:!0,health:1,hunger:0,sanity:0,perish:f,stack:40},petals_evil:{name:"Dark Petals",basename:"Petals.",uncookable:!0,health:0,hunger:0,sanity:-5,perish:f,stack:40},seeds:{name:"Seeds",uncookable:!0,health:0,hunger:4.6875,sanity:0,perish:G,stack:40},seeds_cooked:{name:"Toasted Seeds",uncookable:!0,health:1,hunger:4.6875,sanity:0,perish:g,stack:40},spoiled_food:{name:"Rot",uncookable:!0,health:-1,hunger:-10,sanity:0,
stack:40},tallbirdegg:{name:"Tallbird Egg",egg:4,health:3,hunger:25,sanity:0},tallbirdegg_cooked:{name:"Fried Tallbird Egg",egg:4,precook:1,health:0,hunger:37.5,sanity:0,perish:f},trunk_summer:{name:"Koalefant Trunk",uncookable:!0,ismeat:!0,health:30,hunger:37.5,sanity:0,perish:f,stack:20},trunk_summer_cooked:{name:"Koalefant Trunk Steak",uncookable:!0,ismeat:!0,health:40,hunger:75,sanity:0,perish:r,stack:20},twigs:{name:"Twigs",inedible:1},cavebanana:{name:"Banana",ideal:!0,isfruit:!0,fruit:1,health:1,
hunger:12.5,sanity:0,perish:g},cavebanana_cooked:{name:"Cooked Banana",isfruit:!0,fruit:1,precook:1,health:3,hunger:12.5,sanity:0,perish:f},carrot:{name:"Carrot",isveggie:!0,veggie:1,health:1,hunger:12.5,perish:g,sanity:0,stack:40},carrot_cooked:{name:"Roasted Carrot",isveggie:!0,veggie:1,precook:1,health:3,hunger:12.5,perish:f,sanity:0,stack:40},corn:{name:"Corn",ideal:!0,isveggie:!0,veggie:1,health:3,hunger:25,perish:g,sanity:0,stack:40},corn_cooked:{name:"Popcorn",isveggie:!0,veggie:1,precook:1,
health:3,hunger:12.5,perish:r,sanity:0,stack:40},pumpkin:{name:"Pumpkin",isveggie:!0,veggie:1,health:3,hunger:37.5,perish:g,sanity:0,stack:20},pumpkin_cooked:{name:"Hot Pumpkin",isveggie:!0,veggie:1,precook:1,health:8,hunger:37.5,perish:f,sanity:0,stack:20},eggplant:{name:"Eggplant",isveggie:!0,veggie:1,health:8,hunger:25,perish:g,sanity:0,stack:20},eggplant_cooked:{name:"Braised Eggplant",isveggie:!0,veggie:1,precook:1,health:20,hunger:25,perish:f,sanity:0,stack:20},durian:{name:"Durian",isfruit:!0,
monster:1,fruit:1,health:-3,hunger:25,perish:g,sanity:-5,stack:20},durian_cooked:{name:"Extra Smelly Durian",isfruit:!0,monster:1,fruit:1,precook:1,health:0,hunger:25,perish:f,sanity:-5,stack:20},pomegranate:{name:"Pomegranate",isfruit:!0,fruit:1,health:3,hunger:9.375,perish:f,sanity:0,stack:40},pomegranate_cooked:{name:"Sliced Pomegranate",isfruit:!0,fruit:1,precook:1,health:20,hunger:12.5,perish:u,sanity:0,stack:40},dragonfruit:{name:"Dragon Fruit",isfruit:!0,fruit:1,health:3,hunger:9.375,perish:f,
sanity:0,stack:40},dragonfruit_cooked:{name:"Prepared Dragon Fruit",isfruit:!0,fruit:1,precook:1,health:20,hunger:12.5,perish:u,sanity:0,stack:40},berries:{name:"Berries",isfruit:!0,fruit:.5,health:0,hunger:9.375,perish:f,sanity:0,stack:40},berries_cooked:{name:"Roasted Berries",isfruit:!0,fruit:.5,precook:1,health:1,hunger:12.5,perish:u,sanity:0,stack:40},cactusmeat:{name:"Cactus Flesh",ideal:!0,veggie:1,hunger:12.5,health:-3,perish:g,sanity:-5,stack:40,mode:"giants"},cactusmeat_cooked:{name:"Cooked Cactus Flesh",
veggie:1,hunger:12.5,health:1,perish:g,sanity:15,precook:1,stack:40,mode:"giants"},watermelon:{name:"Watermelon",fruit:1,ideal:!0,hunger:12.5,health:3,perish:f,sanity:5,stack:40,mode:"giants"},watermelon_cooked:{name:"Grilled Watermelon",fruit:1,hunger:12.5,health:1,perish:u,sanity:7.5,precook:1,stack:40,mode:"giants"},wormlight:{name:"Glow Berry",uncookable:!0,health:11,hunger:18.75,sanity:-10,perish:g,note:"Gives 90 seconds of light"},glommerfuel:{name:"Glommer's Goop",uncookable:!0,health:40,hunger:9.375,
sanity:-50,mode:"giants"},coral_brain:{name:"Brainy Matter",uncookable:!0,health:-10,hunger:10,sanity:50,perish:n,mode:"shipwrecked"},blubber:{name:"Blubber",uncookable:!0,health:10,hunger:10,sanity:0,perish:g,stack:10,mode:"shipwrecked"},seaweed:{name:"Seaweed",ideal:!0,veggie:1,health:1,hunger:9.375,sanity:-10,perish:f,stack:40,dry:"seaweed_dried",drytime:q,mode:"shipwrecked"},seaweed_cooked:{name:"Roasted Seaweed",veggie:1,health:3,hunger:9.375,sanity:0,perish:g,stack:40,mode:"shipwrecked"},seaweed_dried:{name:"Dried Seaweed",
veggie:1,health:3,hunger:12.5,sanity:0,perish:E,stack:40,mode:"shipwrecked"},sweet_potato:{name:"Sweet Potato",veggie:1,health:1,hunger:12.5,sanity:0,perish:g,stack:40,mode:"shipwrecked"},sweet_potato_cooked:{name:"Cooked Sweet Potato",veggie:1,health:3,hunger:12.5,sanity:0,perish:f,stack:40,mode:"shipwrecked"},coffeebeans:{name:"Coffee Beans",fruit:.5,health:0,hunger:9.375,sanity:0,perish:f,stack:40,mode:"shipwrecked"},coffeebeans_cooked:{name:"Roasted Coffee Beans",ideal:!0,fruit:1,health:0,hunger:9.375,
sanity:-5,perish:r,stack:40,note:"Gives 5 bonus speed (+83%) for 30 seconds",mode:"shipwrecked"},coconut_halved:{name:"Halved Coconut",basename:"Coconut.",fruit:1,fat:1,health:1,hunger:4.6875,sanity:0,perish:g,stack:40,cook:"coconut_cooked",mode:"shipwrecked"},coconut_cooked:{name:"Roasted Coconut",fruit:1,fat:1,health:1,hunger:9.375,sanity:0,perish:g,stack:40,mode:"shipwrecked"},doydoyegg:{name:"Doydoy Egg",egg:1,health:3,hunger:25,sanity:0,perish:g,mode:"shipwrecked"},doydoyegg_cooked:{name:"Fried Doydoy Egg",
egg:1,health:0,hunger:37.5,sanity:0,perish:f,mode:"shipwrecked"},tropical_fish:{name:"Tropical Fish",skip:!0,ismeat:!0,meat:.5,fish:1,health:1,hunger:12.5,sanity:0,perish:u,stack:40,cook:"fish_raw_small_cooked",dry:"morsel_dried",drytime:q,mode:"shipwrecked"},fish_raw:{name:"Raw Fish",meat:.5,fish:1,health:1,hunger:25,sanity:0,perish:u,stack:40,cook:"fish_med_cooked",dry:"meat_dried",drytime:q,mode:"shipwrecked"},fish_med:{name:"Dead Dogfish",meat:.5,fish:1,health:1,hunger:25,sanity:0,perish:f,stack:40,
rot:"spoiled_fish",dry:"meat_dried",drytime:q,mode:"shipwrecked"},dead_swordfish:{name:"Swordfish",uncookable:!0,health:1,hunger:25,sanity:0,perish:f,stack:40,cook:"fish_med_cooked",rot:"spoiled_fish",dry:"meat_dried",drytime:q,mode:"shipwrecked"},fish_med_cooked:{name:"Fish Steak",meat:.5,fish:1,health:20,hunger:25,sanity:0,perish:f,stack:40,mode:"shipwrecked"},shark_fin:{name:"Shark Fin",meat:.5,fish:1,health:20,hunger:25,sanity:-15,perish:f,stack:10,mode:"shipwrecked"},limpets:{name:"Limpets",
ideal:!0,fish:.5,health:0,hunger:12.5,sanity:-10,perish:f,stack:40,mode:"shipwrecked"},limpets_cooked:{name:"Cooked Limpets",fish:.5,health:1,hunger:12.5,sanity:0,perish:g,stack:40,mode:"shipwrecked"},mussel:{name:"Mussel",fish:.5,health:0,hunger:12.5,sanity:-10,perish:u,stack:40,mode:"shipwrecked"},mussel_cooked:{name:"Cooked Mussel",fish:.5,health:1,hunger:12.5,sanity:0,perish:u,stack:40,mode:"shipwrecked"},mysterymeat:{name:"Bile-Covered Slop",uncookable:!0,health:-1,hunger:-10,sanity:0,stack:20,
mode:"shipwrecked"},jellyfish:{name:"Jellyfish",fish:1,jellyfish:1,monster:1,perish:1.5*n,stack:40,mode:"shipwrecked"},jellyfish_dead:{name:"Dead Jellyfish",basename:"Jellyfish.",fish:1,jellyfish:1,monster:1,health:10,hunger:10,sanity:0,perish:f,stack:20,cook:"jellyfish_cooked",dry:"jellyfish_dried",drytime:q,mode:"shipwrecked"},jellyfish_cooked:{name:"Cooked Jellyfish",fish:1,jellyfish:1,monster:1,health:10,hunger:18.75,sanity:0,perish:g,stack:20,mode:"shipwrecked"},jellyfish_dried:{name:"Dried Jellyfish",
fish:1,jellyfish:1,monster:1,health:10,hunger:18.75,sanity:0,perish:E,stack:20,mode:"shipwrecked"},lobster:{name:"Wobster",fish:2,perish:2*q,mode:"shipwrecked"},lobster_dead:{name:"Dead Wobster",basename:"Wobster.",uncookable:!0,health:1,hunger:12.5,sanity:0,perish:u,stack:10,cook:"lobster_cooked",mode:"shipwrecked"},lobster_cooked:{name:"Delicious Wobster",uncookable:!0,health:1,hunger:12.5,sanity:0,perish:f,stack:40,mode:"shipwrecked"},crab:{name:"Crab",skip:!0,fish:.5,perish:2*q,cook:"fish_raw_small_cooked",
mode:"shipwrecked"},fish_raw_small:{name:"Fish Morsel",fish:.5,health:1,hunger:12.5,perish:u,sanity:0,stack:40,dry:"morsel_dried",drytime:q,mode:"shipwrecked"},fish_raw_small_cooked:{name:"Cooked Fish Morsel",fish:.5,health:1,hunger:12.5,sanity:0,perish:f,stack:40,mode:"shipwrecked"},tigereye:{name:"Eye of the Tiger Shark",uncookable:!0,health:60,hunger:75,sanity:-15,stack:10,mode:"shipwrecked"},dragoonheart:{name:"Dragoon Heart",uncookable:!0,health:11,hunger:25,sanity:-10,perish:g,stack:10,note:"Gives 90 seconds of light",
mode:"shipwrecked"},wormlight_lesser:{name:"Lesser Glowberry",uncookable:!0,health:3,hunger:12.5,sanity:-10,perish:u,stack:40,note:"Gives 22.5 seconds of light",mode:"together"},phlegm:{name:"Phlegm",uncookable:!0,health:0,hunger:12.5,sanity:-15,perish:u,stack:40,mode:"together"}},xa=function(){return this.op+this.qty},ya={"=":function(a){return a===this.qty},">":function(a){return a>this.qty},"<":function(a){return a<this.qty},">=":function(a){return a>=this.qty},"<=":function(a){return a<=this.qty}},
V={test:function(a){return!!a},toString:function(){return""}},n=function(a,d){return{op:a,qty:d,test:ya[a],toString:xa}},za=function(a,d,b){return this.item1.test(a,d,b)&&this.item2.test(a,d,b)},Aa=function(){return this.item1+" and "+this.item2},Ba=function(a,d,b){return this.item1.test(a,d,b)||this.item2.test(a,d,b)},Ca=function(){return this.item1+" or "+this.item2},G=function(a,d){return{item1:a,item2:d,test:Ba,toString:Ca,cancel:a.cancel||d.cancel}},Da=function(a,d,b){return!this.item.test(a,
d,b)},Ea=function(){return this.item.toString().substring(0,this.item.toString().length-1)+"|strike]"},m=function(a){return{item:a,test:Da,toString:Ea,cancel:!0}},Fa=function(a,d,b){return(d[this.name]||0)+(d[this.name+"_cooked"]||0)},Ga=function(){return"[*"+p[this.name].name+"|"+p[this.name].img+" "+p[this.name].name+"]"+(p[this.name].cook?"[*"+p[this.name].cook.name+"|"+p[this.name].cook.img+"]":"")+(p[this.name].raw?"[*"+p[this.name].raw.name+"|"+p[this.name].raw.img+"]":"")+(this.qty?this.qty:
"")},C=function(a,d){return{name:a,qty:d||V,test:Fa,toString:Ga}},Ha=function(a,d,b){return d[this.name]},Ia=function(){return"[*"+p[this.name].name+"|"+p[this.name].img+" "+p[this.name].name+"]"+(this.qty?this.qty:"")},v=function(a,d){return{name:a,qty:d||V,test:Ha,toString:Ia}},Ja=function(a,d,b){return b[this.tag]},Ka=function(){return"[tag:"+this.tag+"|"+this.tag+"]"+(this.qty?this.qty:"")},e=function(a,d){return{tag:a,qty:d||V,test:Ja,toString:Ka}},k={butterflymuffin:{name:"Butter Muffin",test:function(a,
d,b){return d.butterflywings&&!b.meat&&b.veggie},requires:"Butterfly Wings, veggie",requirements:[C("butterflywings"),m(e("meat")),e("veggie")],priority:1,weight:1,foodtype:"veggie",health:20,hunger:37.5,perish:r,sanity:5,cooktime:2},frogglebunwich:{name:"Froggle Bunwich",test:function(a,d,b){return(d.froglegs||d.froglegs_cooked)&&b.veggie},requirements:[C("froglegs"),e("veggie")],priority:1,foodtype:"meat",health:20,hunger:37.5,perish:r,sanity:5,cooktime:2},taffy:{name:"Taffy",test:function(a,d,
b){return b.sweetener&&3<=b.sweetener&&!b.meat},requirements:[e("sweetener",n(">=",3)),m(e("meat"))],priority:10,foodtype:"veggie",health:-3,hunger:25,perish:r,sanity:15,cooktime:2,tags:["honeyed"]},pumpkincookie:{name:"Pumpkin Cookie",test:function(a,d,b){return(d.pumpkin||d.pumpkin_cooked)&&b.sweetener&&2<=b.sweetener},requirements:[C("pumpkin"),e("sweetener",n(">=",2))],priority:10,foodtype:"veggie",health:0,hunger:37.5,perish:g,sanity:15,cooktime:2,tags:["honeyed"]},stuffedeggplant:{name:"Stuffed Eggplant",
test:function(a,d,b){return(d.eggplant||d.eggplant_cooked)&&b.veggie&&1<b.veggie},requirements:[C("eggplant"),e("veggie",n(">",1))],priority:1,foodtype:"veggie",health:3,hunger:37.5,perish:r,sanity:5,temperature:40,temperatureduration:5,cooktime:2},fishsticks:{name:"Fishsticks",test:function(a,d,b){return b.fish&&d.twigs&&b.inedible&&1>=b.inedible},requirements:[e("fish"),v("twigs"),e("inedible"),e("inedible",n("<=",1))],priority:10,foodtype:"meat",health:40,hunger:37.5,perish:g,sanity:5,cooktime:2},
honeynuggets:{name:"Honey Nuggets",test:function(a,d,b){return d.honey&&b.meat&&1.5>=b.meat&&!b.inedible},requirements:[v("honey"),e("meat",n("<=",1.5)),m(e("inedible"))],priority:2,foodtype:"meat",health:20,hunger:37.5,perish:r,sanity:5,cooktime:2,tags:["honeyed"]},honeyham:{name:"Honey Ham",test:function(a,d,b){return d.honey&&b.meat&&1.5<b.meat&&!b.inedible},requirements:[v("honey"),e("meat",n(">",1.5)),m(e("inedible"))],priority:2,foodtype:"meat",health:30,hunger:75,perish:r,sanity:5,temperature:40,
temperatureduration:10,cooktime:2,tags:["honeyed"]},dragonpie:{name:"Dragonpie",test:function(a,d,b){return(d.dragonfruit||d.dragonfruit_cooked)&&!b.meat},requirements:[C("dragonfruit"),m(e("meat"))],priority:1,foodtype:"veggie",health:40,hunger:75,perish:r,sanity:5,temperature:40,temperatureduration:10,cooktime:2},kabobs:{name:"Kabobs",test:function(a,d,b){return b.meat&&d.twigs&&(!b.monster||1>=b.monster)&&b.inedible&&1>=b.inedible},requirements:[e("meat"),v("twigs"),G(m(e("monster")),e("monster",
n("<=",1))),e("inedible"),e("inedible",n("<=",1))],priority:5,foodtype:"meat",health:3,hunger:37.5,perish:r,sanity:5,cooktime:2},mandrakesoup:{name:"Mandrake Soup",test:function(a,d,b){return d.mandrake},requirements:[v("mandrake")],priority:10,foodtype:"veggie",health:100,hunger:150,perish:f,sanity:5,cooktime:3},baconeggs:{name:"Bacon and Eggs",test:function(a,d,b){return b.egg&&1<b.egg&&b.meat&&1<b.meat&&!b.veggie},requirements:[e("egg",n(">",1)),e("meat",n(">",1)),m(e("veggie"))],priority:10,foodtype:"meat",
health:20,hunger:75,perish:E,sanity:5,cooktime:2},meatballs:{name:"Meatballs",test:function(a,d,b){return b.meat&&!b.inedible},requirements:[e("meat"),m(e("inedible"))],priority:-1,foodtype:"meat",health:3,hunger:62.5,perish:g,sanity:5,cooktime:.75},bonestew:{name:"Meaty Stew",test:function(a,d,b){return b.meat&&3<=b.meat&&!b.inedible},requirements:[e("meat",n(">=",3)),m(e("inedible"))],priority:0,foodtype:"meat",health:12,hunger:150,perish:g,sanity:5,temperature:40,temperatureduration:15,cooktime:.75},
perogies:{name:"Pierogi",test:function(a,d,b){return b.egg&&b.meat&&b.veggie&&!b.inedible},requirements:[e("egg"),e("meat"),e("veggie"),m(e("inedible"))],priority:5,foodtype:"meat",health:40,hunger:37.5,perish:E,sanity:5,temperature:40,temperatureduration:10,cooktime:1},turkeydinner:{name:"Turkey Dinner",test:function(a,d,b){return d.drumstick&&1<d.drumstick&&b.meat&&1<b.meat&&(b.veggie||b.fruit)},requirements:[v("drumstick",n(">",1)),e("meat",n(">",1)),G(e("veggie"),e("fruit"))],priority:10,foodtype:"meat",
health:20,hunger:75,perish:f,sanity:5,temperature:40,temperatureduration:10,cooktime:3},ratatouille:{name:"Ratatouille",test:function(a,d,b){return!b.meat&&b.veggie&&!b.inedible},requirements:[m(e("meat")),e("veggie"),m(e("inedible"))],priority:0,foodtype:"veggie",health:3,hunger:25,perish:r,sanity:5,temperature:-40,temperatureduration:5,cooktime:1},jammypreserves:{name:"Fist Full of Jam",test:function(a,d,b){return b.fruit&&!b.meat&&!b.veggie&&!b.inedible},requirements:[e("fruit"),m(e("meat")),m(e("veggie")),
m(e("inedible"))],priority:0,foodtype:"veggie",health:3,hunger:37.5,perish:r,sanity:5,cooktime:.5},fruitmedley:{name:"Fruit Medley",test:function(a,d,b){return b.fruit&&3<=b.fruit&&!b.meat&&!b.veggie},requirements:[e("fruit",n(">=",3)),m(e("meat")),m(e("veggie"))],priority:0,foodtype:"veggie",health:20,hunger:25,perish:f,sanity:5,temperature:-40,temperatureduration:5,cooktime:.5},fishtacos:{name:"Fish Tacos",test:function(a,d,b){return b.fish&&(d.corn||d.corn_cooked)},requirements:[e("fish"),C("corn")],
priority:10,foodtype:"meat",health:20,hunger:37.5,perish:f,sanity:5,cooktime:.5,tags:["monstermeat"]},waffles:{name:"Waffles",test:function(a,d,b){return d.butter&&(d.berries||d.berries_cooked)&&b.egg},requirements:[v("butter"),C("berries"),e("egg")],priority:10,foodtype:"veggie",health:60,hunger:37.5,perish:f,sanity:5,cooktime:.5},monsterlasagna:{name:"Monster Lasagna",test:function(a,d,b){return b.monster&&2<=b.monster&&!b.inedible},requirements:[e("monster",n(">=",2)),m(e("inedible"))],priority:10,
foodtype:"meat",health:-20,hunger:37.5,perish:f,sanity:-20,cooktime:.5},powcake:{name:"Powdercake",test:function(a,d,b){return d.twigs&&d.honey&&(d.corn||d.corn_cooked)},requirements:[v("twigs"),v("honey"),C("corn")],priority:10,foodtype:"veggie",health:-3,hunger:0,perish:9E6,sanity:0,cooktime:.5,tags:["honeyed"]},unagi:{name:"Unagi",test:function(a,d,b){return d.cutlichen&&(d.eel||d.eel_cooked)},requirements:[v("cutlichen"),C("eel")],priority:20,foodtype:"veggie",health:20,hunger:18.75,perish:g,
sanity:5,cooktime:.5},wetgoop:{name:"Wet Goop",test:function(a,d,b){return!0},requirements:[],trash:!0,priority:-2,health:0,hunger:0,perish:f,sanity:0,cooktime:.25},flowersalad:{name:"Flower Salad",test:function(a,d,b){return d.cactusflower&&b.veggie&&2<=b.veggie&&!b.meat&&!b.inedible&&!b.egg&&!b.sweetener&&!b.fruit},requirements:[v("cactusflower"),e("veggie",n(">=",2)),m(e("meat")),m(e("inedible")),m(e("egg")),m(e("sweetener")),m(e("fruit"))],priority:10,foodtype:"veggie",health:40,hunger:12.5,perish:f,
sanity:5,cooktime:.5,mode:"giants"},icecream:{name:"Ice Cream",test:function(a,d,b){return b.frozen&&b.dairy&&b.sweetener&&!b.meat&&!b.veggie&&!b.inedible&&!b.egg},requirements:[e("frozen"),e("dairy"),e("sweetener"),m(e("meat")),m(e("veggie")),m(e("inedible")),m(e("egg"))],priority:10,foodtype:"veggie",health:0,hunger:25,perish:u,sanity:50,temperature:-40,temperatureduration:15,cooktime:.5,mode:"giants"},watermelonicle:{name:"Melonsicle",test:function(a,d,b){return d.watermelon&&b.frozen&&d.twigs&&
!b.meat&&!b.veggie&&!b.egg},requirements:[v("watermelon"),e("frozen"),v("twigs"),m(e("meat")),m(e("veggie")),m(e("egg"))],priority:10,foodtype:"veggie",health:3,hunger:12.5,perish:u,sanity:20,temperature:-40,temperatureduration:10,cooktime:.5,mode:"giants"},trailmix:{name:"Trail Mix",test:function(a,d,b){return d.acorn_cooked&&b.seed&&1<=b.seed&&(d.berries||d.berries_cooked)&&b.fruit&&1<=b.fruit&&!b.meat&&!b.veggie&&!b.egg&&!b.dairy},requirements:[v("acorn_cooked"),e("seed",n(">=",1)),C("berries"),
e("fruit",n(">=",1)),m(e("meat")),m(e("veggie")),m(e("egg")),m(e("dairy"))],priority:10,foodtype:"veggie",health:30,hunger:12.5,perish:r,sanity:5,cooktime:.5,mode:"giants"},hotchili:{name:"Spicy Chili",test:function(a,d,b){return b.meat&&b.veggie&&1.5<=b.meat&&1.5<=b.veggie},requirements:[e("meat",n(">=",1.5)),e("veggie",n(">=",1.5))],priority:10,foodtype:"meat",health:20,hunger:37.5,perish:g,sanity:0,temperature:40,temperatureduration:15,cooktime:.5,mode:"giants"},guacamole:{name:"Guacamole",test:function(a,
d,b){return d.mole&&d.cactusmeat&&!b.fruit},requirements:[v("mole"),v("cactusmeat"),m(e("fruit"))],priority:10,foodtype:"meat",health:20,hunger:37.5,perish:g,sanity:0,cooktime:.5,mode:"giants"},californiaroll:{name:"California Roll",test:function(a,d,b){return d.seaweed&&2===d.seaweed&&b.fish&&1<=b.fish},requirements:[v("seaweed",n("=",2)),e("fish",n(">=",1))],priority:20,foodtype:"meat",health:20,hunger:37.5,perish:g,sanity:10,cooktime:.5,mode:"shipwrecked"},seafoodgumbo:{name:"Seafood Gumbo",test:function(a,
d,b){return b.fish&&2<b.fish},requirements:[e("fish",n(">",2))],priority:10,foodtype:"meat",health:40,hunger:37.5,perish:g,sanity:20,cooktime:1,mode:"shipwrecked"},bisque:{name:"Bisque",test:function(a,d,b){return d.limpets&&3===d.limpets&&b.frozen},requirements:[v("limpets",n("=",3)),e("frozen")],priority:30,foodtype:"meat",health:60,hunger:18.75,perish:g,sanity:5,cooktime:1,mode:"shipwrecked"},ceviche:{name:"Ceviche",test:function(a,d,b){return b.fish&&2<=b.fish&&b.frozen},requirements:[e("fish",
n(">=",2)),e("frozen")],priority:20,foodtype:"meat",health:20,hunger:25,perish:g,sanity:5,temperature:-40,temperatureduration:10,cooktime:.5,mode:"shipwrecked"},jellyopop:{name:"Jelly-O Pop",test:function(a,d,b){return b.jellyfish&&b.frozen&&b.inedible},requirements:[e("jellyfish"),e("frozen"),e("inedible")],priority:20,foodtype:"meat",health:20,hunger:12.5,perish:u,sanity:0,temperature:-40,temperatureduration:10,cooktime:.5,mode:"shipwrecked"},bananapop:{name:"Banana Pop",test:function(a,d,b){return d.cavebanana&&
b.frozen&&b.inedible&&!b.meat&&!b.fish},requirements:[v("cavebanana"),e("frozen"),e("inedible"),m(e("meat")),m(e("fish"))],priority:20,foodtype:"veggie",health:20,hunger:12.5,perish:u,sanity:33,temperature:-40,temperatureduration:10,cooktime:.5,mode:"shipwrecked"},lobsterbisque:{name:"Lobster Bisque",test:function(a,d,b){return d.lobster&&b.frozen},requirements:[v("lobster"),e("frozen")],priority:30,foodtype:"meat",health:60,hunger:25,perish:g,sanity:10,cooktime:.5,mode:"shipwrecked"},lobsterdinner:{name:"Lobster Dinner",
test:function(a,d,b){return d.lobster&&d.butter&&!b.meat&&!b.frozen},requirements:[v("lobster"),v("butter"),m(e("meat")),m(e("frozen"))],priority:25,foodtype:"meat",health:60,hunger:37.5,perish:r,sanity:50,cooktime:1,mode:"shipwrecked"},sharkfinsoup:{name:"Shark Fin Soup",test:function(a,d,b){return d.shark_fin},requirements:[v("shark_fin")],priority:20,foodtype:"meat",health:40,hunger:12.5,perish:g,sanity:-10,cooktime:1,note:"Gives 10 naughtiness",mode:"shipwrecked"},surfnturf:{name:"Surf 'n' Turf",
test:function(a,d,b){return b.meat&&2.5<=b.meat&&b.fish&&1.5<=b.fish&&!b.frozen},requirements:[e("meat",n(">=",2.5)),e("fish",n(">=",1.5)),m(e("frozen"))],priority:30,foodtype:"meat",health:60,hunger:37.5,perish:g,sanity:33,cooktime:1,mode:"shipwrecked"},coffee:{name:"Coffee",test:function(a,d,b){return d.coffeebeans_cooked&&(4===d.coffeebeans_cooked||3===d.coffeebeans_cooked&&(b.dairy||b.sweetener))},requirements:[G(v("coffeebeans_cooked",n("=",4)),function(a,d){return{item1:a,item2:d,test:za,toString:Aa,
cancel:a.cancel&&d.cancel}}(v("coffeebeans_cooked",n("=",3)),G(e("dairy"),e("sweetener"))))],priority:30,foodtype:"veggie",health:3,hunger:9.375,perish:g,sanity:-5,cooktime:.5,note:"Gives 5 bonus speed (+83%) for 0.5 days",mode:"shipwrecked"},sweetpotatosouffle:{name:"Sweet Potato Souffle",test:function(a,d,b){return d.sweet_potato&&2===d.sweet_potato&&b.egg&&2<=b.egg},requirements:[v("sweet_potato",n("=",2)),e("egg",n(">=",2))],priority:30,foodtype:"veggie",health:20,hunger:37.5,perish:g,sanity:15,
cooktime:2,mode:"warly"},monstertartare:{name:"Monster Tartare",test:function(a,d,b){return b.monster&&2<=b.monster&&b.egg&&b.veggie},requirements:[e("monster",n(">=",2)),e("egg"),e("veggie")],priority:30,foodtype:"meat",health:3,hunger:37.5,perish:g,sanity:10,cooktime:2,mode:"warly"},freshfruitcrepes:{name:"Fresh Fruit Crepes",test:function(a,d,b){return b.fruit&&1.5<=b.fruit&&d.butter&&d.honey},requirements:[e("fruit",n(">=",1.5)),v("butter"),v("honey")],priority:30,foodtype:"veggie",health:60,
hunger:150,perish:g,sanity:15,cooktime:2,mode:"warly"},musselbouillabaise:{name:"Mussel Bouillabaise",test:function(a,d,b){return d.mussel&&2===d.mussel&&b.veggie&&2<=b.veggie},requirements:[v("mussel",n("=",2)),e("veggie",n(">=",2))],priority:30,foodtype:"meat",health:20,hunger:37.5,perish:g,sanity:15,cooktime:2,mode:"warly"}},O=function(){var a,d,b=/^tag[: ]/,c=/^tag:? */,l=/^tagnot[: ]/,e=/^tagnot:? */,y,g=/^recipe[: ]/,f=/^recipe:? */,h,m=/^ingredient[: ]/,Ma=/^ingredient:? */,ma,na,n=!1,q=function(b){!n&&
b.uncookable||0===(b.modeMask&B)?b.match=0:0===b.lowerName.indexOf(a)||b.raw&&0===b.raw.lowerName.indexOf(a)?b.match=3:0===na.test(b.lowerName)?b.match=2:ma.test(b.lowerName)?b.match=1:b.match=0;return b.match},t=function(a){return a.match=a[d]+0||0},v=function(a){for(var b=0,d,c=!0;b<y.length;){d=y[b].test(null,a.nameObject,a);if(y[b].cancel){if(!d){c=!0;break}}else d&&(c=!1);b++}return a.match=c?0:1},u=function(a){for(var b=0,d,c=!0;b<a.requirements.length;){d=a.requirements[b].test(null,h.nameObject,
h);if(a.requirements[b].cancel){if(!d){c=!0;break}}else d&&(c=!1);b++}return a.match=c?0:1},N=function(b){return b.match=b.lowerName===a?1:0},W=function(b){return b.match=b.lowerName===a||b.raw&&b.raw.lowerName===a||b.cook&&b.cook.lowerName===a?1:0},r=function(a,b){if(a.match===b.match){var d=a.basename?a.basename:a.name;var c=b.basename?b.basename:b.name;return d!==c?d>c?1:d<c?-1:0:a.name===b.name?0:a.raw===b?1:-1}return b.match-a.match};return function(w,K,La){n=!!La;a=K.toLowerCase();if(b.test(a))return d=
a.split(c)[1],w.filter(t).sort(r);if(l.test(a))return d=a.split(e)[1],w.filter(function(a){return!t(a)}).sort(r);if(g.test(a))return(y=k.byName(a.split(f)[1].toLowerCase()))?(y=y.requirements,w.filter(v).sort(r)):[];if(m.test(a))return(h=p.byName(a.split(Ma)[1].toLowerCase()))?w.filter(u).sort(r):[];if(0===a.indexOf("*"))return a=a.substring(1),w.filter(N).sort(r);if(0===a.indexOf("~"))return a=a.substring(1),w.filter(W).sort(r);na=new RegExp("\\b"+a+".*");ma=new RegExp("\\b"+a.split("").join(".*")+
".*");return w.filter(q).sort(r)}}(),ea=function(a,d,b){var c,l;for(c=0;c<a.length;c++){var e=a[c];if(null!==e)for(l in d[e.id]=1+(d[e.id]||0),e)if(e.hasOwnProperty(l)&&"perish"!==l&&!isNaN(e[l])){var y=e[l];ua[l]?y*=A[e.preparationType]:va[l]&&(y*=A[e[l+"Type"]]);b[l]=y+(b[l]||0)}else"perish"===l&&(b[l]=Math.min(b[l]||E,e[l]))}},oa=function(){var a,d;return function(b,c,e,g){var l;b.length=0;a={};d={};ea(c,a,d);d.hunger=d.bestHunger;d.health=d.bestHealth;d.sanity=d.bestSanity;c=0;a:for(;c<k.length;c++){var w=
!1;if(0!==(k[c].modeMask&B)){for(l=0;l<k[c].requirements.length;l++)if(k[c].requirements[l].test(null,a,d))k[c].requirements[l].cancel||(w=!0);else if(!g&&k[c].requirements[l].cancel)continue a;else if(g&&!k[c].requirements[l].cancel)continue a;!w||e&&-1!==e.indexOf(k[c])||b.push(k[c])}}d.img="";d.name="Combined";return b}}(),Na=function(){var a=[],d,b;return function(c){a.length=0;d={};b={};ea(c,d,b);b.hunger=b.bestHunger;b.health=b.bestHealth;b.sanity=b.bestSanity;for(c=0;c<k.length;c++)k[c].test(null,
d,b)&&0!==(k[c].modeMask&B)&&a.push(k[c]);a.sort(function(a,b){return b.priority-a.priority});b.img="";b.name="Combined";b.priority=" ";b.perish=0;b.cooktime=0;a.unshift(b);return a}}(),M=function(){var a=document.createElement("canvas"),d=a.getContext&&a.toDataURL&&a.getContext("2d"),b=document.createElement("canvas"),c=b.getContext&&b.getContext("2d"),e={},g={},y=!!d,f=[],k=function(l){var w=function(l,w){d.clearRect(0,0,64,64);d.drawImage(w,0,0,64,64);c.clearRect(0,0,32,32);c.drawImage(w,0,0,32,
32);try{e[l]=a.toDataURL(),g[l]=b.toDataURL()}catch(Va){y=!1}f.filter(function(a){return a.url===l}).forEach(function(a){a.url===l&&(delete a.img.dataset.pending,S&&a.img.removeAttribute("data-pending"),a.img.src=32===a.d?g[l]||l:e[l]||l)});f=f.filter(function(a){return a.url!==l})};return function(a){w(l,a.target)}},h=function(a,b,d){a.dataset.pending=b;S&&a.setAttribute("data-pending",b);f.push({url:b,img:a,d:d})},p=function(a,b){var d=new Image;if(y)if(e[a])d.src=32===b?g[a]:e[a];else{if(null!==
e[a]){e[a]=null;var c=new Image;c.addEventListener("load",k(a),!1);c.src=a}h(d,a,b)}else d.src=a;return d};a.width=64;a.height=64;b.width=32;b.height=32;p.queue=h;return p}(),fa=function(){var a=/\[([^\|]*)\|([^\|\]]*)\|?([^\|\]]*)\]/,d=/([^\|]\]\[[^\|]+\|[^\|\]]+)\|?([^\|\](?:left)]*)(?=\])/g,b=/(\[[^\|]+\|[^\|\]]+)\|?([^\|\]]*)(?=\]\[)(?!\]\[\|)/g,c=function(a,b,d){return b+"|"+(0===d.length?"left":d+" left")},e=function(a,b,d){return b+"|"+(0===d.length?"right":d+" right")},g=/_(\w)/g,y=function(a,
b){return" "+b.toUpperCase()};return function(l){var w=l&&l.replace(d,c).replace(d,c).replace(b,e);l=w&&w.split(a);var f;if(l&&1!==l.length)for(w=document.createDocumentFragment(),w.appendChild(document.createTextNode(l[0])),f=1;f<l.length;f+=4){if(""===l[f]&&""===l[f+1])w.appendChild(document.createElement("br"));else{var k=document.createElement("span");k.className=""===l[f+2]?"link":"link "+l[f+2];k.dataset.link=l[f];S&&k.setAttribute("data-link",l[f]);if(l[f+1]&&0===l[f+1].indexOf("img/")){k.appendChild(document.createTextNode(l[f+
1].split(" ").slice(1).join(" ")));var h=l[f+1].split(" ")[0];var K=M(h,32);K.title=(h.substr(4,1).toUpperCase()+h.substr(5).replace(g,y)).split(".")[0];k.appendChild(K)}else k.appendChild(document.createTextNode(l[f+1]?l[f+1]:l[f]));w.appendChild(k)}w.appendChild(document.createTextNode(l[f+3]))}return w}}(),h,u=0,pa=document.getElementById("main"),Oa=document.getElementById("food"),Pa=document.getElementById("recipes"),ga=document.getElementById("navbar"),S=!1;document.documentElement.dataset||
(S=!0,Object.defineProperty(Element.prototype,"dataset",{get:function(){this.ds||(this.ds={},Array.prototype.forEach.call(this.attributes,function(a){0===a.name.indexOf("data-")&&(this.ds[a.name.substring(5)]=a.value)},this));return this.ds}}));document.getElementById("stalehealth").appendChild(document.createTextNode(Math.round(333)/10+"%"));document.getElementById("stalehunger").appendChild(document.createTextNode(Math.round(667)/10+"%"));document.getElementById("spoiledhunger").appendChild(document.createTextNode(Math.round(500)/
10+"%"));document.getElementById("spoiledsanity").appendChild(document.createTextNode(10));document.getElementById("perishground").appendChild(document.createTextNode(Math.round(1500)/10+"%"));document.getElementById("perishwinter").appendChild(document.createTextNode(Math.round(750)/10+"%"));document.getElementById("perishsummer").appendChild(document.createTextNode(Math.round(1250)/10+"%"));document.getElementById("perishfridge").appendChild(document.createTextNode(Math.round(500)/10+"%"));f=function(a,
d){return"[tag:"+a+"|"+(d||a)+"]"};for(h in p)if(p.hasOwnProperty(h)){var c=p[h];c.match=0;c.lowerName=c.name.toLowerCase();c.id=h;c.nameObject={};c.nameObject[h]=1;c.img="img/"+c.name.replace(/ /g,"_").replace(/'/g,"").toLowerCase()+".png";c.preparationType=c.preparationType||"raw";p[h+"_cooked"]&&(c.cook=p[h+"_cooked"]);"string"===typeof c.cook&&(c.cook=p[c.cook]);c.cook&&!c.cook.raw&&(c.cook.raw=c,c.cook.cooked=!0,c.cook.basename||(c.cook.basename=(c.basename||c.name)+"."));"string"===typeof c.raw&&
(c.raw=p[c.raw],c.cooked=!0,c.basename||(c.basename=(c.raw.basename||c.raw.name)+"."));"string"===typeof c.dry&&(c.dry=p[c.dry]);c.dry&&!c.dry.wet&&(c.dry.wet=c,c.dry.rackdried=!0,c.dry.basename||(c.dry.basename=(c.basename||c.name)+".."));"string"===typeof c.wet&&(c.rackdried=!0,c.wet=p[c.wet],c.basename||(c.basename=(c.wet.basename||c.wet.name)+".."));c.cook&&(c.cook.preparationType="cooked");c.dry&&(c.dry.preparationType="dried");for(h=0;h<H.length;h++)g=H[h],r=c[g]||0,n=c.preparationType,c.raw&&
(r=Math.max(c.raw[g]||0,r),r===c.raw[g]&&(n="raw")),c.cook&&(r=Math.max(c.cook[g]||0,r),r===c.cook[g]&&(n="cooked")),g=g.charAt(0).toUpperCase()+g.slice(1),c["best"+g]=r,c["best"+g+"Type"]=n;c.info=[];g=c.info;c.fruit&&g.push(f("fruit")+(1===c.fruit?"":"\u00d7"+c.fruit));c.veggie&&g.push(f("veggie","vegetable")+(1===c.veggie?"":"\u00d7"+c.veggie));c.meat&&g.push(f("meat")+(1===c.meat?"":"\u00d7"+c.meat));c.egg&&g.push(f("egg")+(1===c.egg?"":"\u00d7"+c.egg));c.fish&&g.push(f("fish")+(1===c.fish?"":
"\u00d7"+c.fish));c.magic&&g.push(f("magic"));c.decoration&&g.push(f("decoration"));c.inedible&&g.push(f("inedible"));c.monster&&g.push(f("monster","monster food"));c.sweetener&&g.push(f("sweetener"));c.fat&&g.push(f("fat"));c.dairy&&g.push(f("dairy"));c.comment&&g.push(c.comment);p[u++]=c}p.length=u;u=0;for(h in k)k.hasOwnProperty(h)&&(k[h].match=0,k[h].name=k[h].name||h,k[h].id=h,k[h].lowerName=k[h].name.toLowerCase(),k[h].weight=k[h].weight||1,k[h].priority=k[h].priority||0,k[h].img="img/"+k[h].name.replace(/ /g,
"_").replace(/'/g,"").toLowerCase()+".png",k[h].requirements&&(k[h].requires=fa(k[h].requirements.join("; ")+(k[h].mode?"; [tag:"+k[h].mode+"|img/"+x[k[h].mode].img+"]":""))),k[h].mode?k[h][k[h].mode]=!0:(k[h].vanilla=!0,k[h].mode="vanilla"),k[h].modeMask=x[k[h].mode].bit,k[h].temperature&&(k[h].note=k[h].note?k[h].note+"; ":"",k[h].note+="Provides "+k[h].temperature+" heat for "+k[h].temperatureduration+" seconds"),k[h].preparationType="recipe",k[u++]=k[h]);k.length=u;k.forEach=Array.prototype.forEach;
k.filter=Array.prototype.filter;k.sort=Array.prototype.sort;k.byName=function(a){for(var d=this.length;d--;)if(this[d].lowerName===a)return this[d]};var H=function(a,d){return a+"[recipe:"+d.name+"|"+d.img+"]"},ha=function(a,d,b){return 1===d?a:a+(b||"s")};for(h=0;h<p.length;h++)c=p[h],g=c.info,c.cooked&&g.push("from [*"+c.raw.name+"|"+c.raw.img+"]"),c.cook&&(c.cook instanceof Object||(c.cook=p[c.cook]),g.push("cook: [*"+c.cook.name+"|"+c.cook.img+"]")),c.dry&&(c.dry instanceof Object||(c.dry=p[c.dry]),
g.push("dry in "+c.drytime/q+" "+ha("day",c.drytime/q)+": [*"+c.dry.name+"|"+c.dry.img+"]")),c.mode?(c[c.mode]=!0,g.push("requires [tag:"+c.mode+"|img/"+x[c.mode].img+"]")):(c.vanilla=!0,c.mode="vanilla"),c.modeMask=x[c.mode].bit,c.info=g.join("; "),c.uncookable?c.info+=(c.info?"[|]":"")+"cannot be added to crock pot":(c.recipes=[],k.forEach(function(a){for(var d=!1,b=a.requirements,e=b.length;e--;)if(b[e].test(null,c.nameObject,c))b[e].cancel||d||(d=!0);else if(b[e].cancel){d=!1;break}d&&c.recipes.push(a)}),
0<c.recipes.length&&(c.ingredient=!0,c.info+=c.recipes.reduce(H,"[|][ingredient:"+c.name+"|Recipes] "))),c.note&&(c.info+="[|]"+c.note),c.info=fa(c.info);p.forEach=Array.prototype.forEach;p.filter=Array.prototype.filter;p.sort=Array.prototype.sort;p.byName=function(a){for(var d=this.length;d--;)if(this[d].lowerName===a)return this[d]};var Qa=function(a,d,b){var c=b||[0,0,0,0],l,e=0,g=0;return function(b){for(var f;b--&&1<=a;){d(c);c[0]++;for(f=0;c[f]>=a;)f++,c[f]++;l=4;for(e=0;l--;)c[l]>=a?c[l]=e:
c[l]>e&&(e=c[l]);if(4===f)return!1;g++}return!0}};var ia=J=void 0;J=k.filter(function(a){return!a.trash}).sort(function(a,d){return d.priority-a.priority});ia=J.map(function(a){return a.test});J.map(function(a){return a.test.toString()});J.map(function(a){return a.priority});var Ra=function(a,d,b,c){var l=ia.length,e=[],f=0,g,w=60,k=function(b){return a[b]},h=Qa(a.length,function(a){a=a.map(k);var b,d=null,c={},f={},g=null,w=!1,y=ia,h=J;ea(a,c,f);f.hunger=f.bestHunger;f.health=f.bestHealth;f.sanity=
f.bestSanity;for(b=0;b<l&&(null===d||h[b].priority>=d);b++)y[b](null,c,f)&&(null!==g&&(w=!0,g.multiple=!0),g={recipe:h[b],ingredients:a,tags:{health:f.health,hunger:f.hunger},multiple:w},e.push(g),d=h[b].priority)}),p=function(){var a=!1,l=Date.now();for(h(w)?setTimeout(p,0):a=!0;f<e.length&&e[f];f++)d(e[f]);g!==Date.now()-l&&(g=Date.now()-l+1,w=38/g*w+1|0);b&&b();a&&c&&c()};p()},T;(function(){var a=ga.getElementsByTagName("li"),d={},b={},c=function(a){T(a.target.dataset.tab)};T=function(a){f.className=
"";f=d[a];g.style.display="none";g=b[a];f.className="selected";g.style.display="block"};for(h=0;h<a.length;h++){var e=a[h];e.dataset.tab&&(d[e.dataset.tab]=e,b[e.dataset.tab]=document.getElementById(e.dataset.tab),b[e.dataset.tab].style.display="none",e.addEventListener("selectstart",function(a){a.preventDefault()},!1),e.addEventListener("click",c,!1))}var f=d.simulator;var g=b.simulator;window.localStorage&&localStorage.foodGuideState&&(a=JSON.parse(localStorage.foodGuideState),a.activeTab&&d[a.activeTab]&&
(f=d[a.activeTab],g=b[a.activeTab],B=a.modeMask||x.shipwrecked.mask));f.className="selected";g.style.display="block";window.addEventListener("beforeunload",function(){if(window.localStorage){localStorage.foodGuideState||(localStorage.foodGuideState="{}");var a=JSON.parse(localStorage.foodGuideState);a.activeTab=f.dataset.tab;a.modeMask=B;localStorage.foodGuideState=JSON.stringify(a)}})})();var Sa=function(a){a.dataset.pending&&M.queue(a,a.dataset.pending,32)},ja=function(a){var d,b,c=document.createElement("tr");
for(d=1;d<arguments.length;d++){var e=document.createElement(a);var f=(b=arguments[d])&&b.indexOf?b:b.toString();b instanceof DocumentFragment?(e.appendChild(b.cloneNode(!0)),Array.prototype.forEach.call(e.getElementsByTagName("img"),Sa)):0===f.indexOf("img/")?(b=M(f),e.appendChild(b)):b&&b.nodeType&&1===b.nodeType?e.appendChild(b):e.appendChild(document.createTextNode(f));c.appendChild(e)}return c},qa=function(a){if(a&&"Combined"===a)return a;var d=document.createElement("a");d.setAttribute("target",
"_blank");d.setAttribute("href","http://dontstarve.wikia.com/wiki/"+a.replace(/\s/g,"_"));a=document.createTextNode(a);d.appendChild(a);return d},U=function(a,d,b,c,e,f,g,k,h,p){var l,w,y,n=!1,m,K,t,q=function(a,d,c){p&&!(t<p)||k&&!k(a)||(d=b(a),g&&g(a,c)&&(d.className="highlighted",m||(m=d),K=d),l.appendChild(d),t++)},r=function(b,c,g){var k;if(c||b&&""!==b.target.dataset.sort||y){var h=c||b&&b.target.dataset.sort||y;e&&(k=d.shift());"name"===h?d.sort(function(a,b){var d=a.basename?a.basename:a.name,
c=b.basename?b.basename:b.name;return d!==c?d>c?1:d<c?-1:0:a.name===b.name?0:a.raw===b?1:-1}):d.sort(function(a,b){var d=a[h],c=b[h];return isNaN(d)||isNaN(c)?isNaN(d)&&isNaN(c)?0:isNaN(d)?1:-1:c-d});if(c||b)y===h?n=!n:(y=h,n=!1);n&&d.reverse();e&&d.unshift(k)}b=document.createElement("tr");for(w in a)c=document.createElement("th"),-1===w.indexOf(":")?c.appendChild(document.createTextNode(w)):(c.appendChild(document.createTextNode(w.split(":")[0])),c.title=w.split(":")[1]),a[w]&&(a[w]===y&&(c.style.background=
n?"#555":"#ccc",c.style.color=n?"#ccc":"#555",c.style.borderRadius="4px"),c.style.cursor="pointer",c.dataset.sort=a[w],c.addEventListener("click",r,!1)),b.appendChild(c);c=l;l=document.createElement("table");l.appendChild(b);K=m=null;t=0;d.forEach(q);f&&(l.className="links",Array.prototype.forEach.call(l.getElementsByClassName("link"),function(a){a.addEventListener("click",f,!1)}));c&&c.parentNode.replaceChild(l,c);g&&(m&&m.offsetTop+l.offsetTop+pa.offsetTop+m.offsetHeight>window.scrollY+window.innerHeight?
m.scrollIntoView(!0):K&&K.offsetTop+l.offsetTop+pa.offsetTop<window.scrollY&&K.scrollIntoView(!1))};c?r(null,c):r();l.update=function(a){r(null,null,a)};l.setMaxRows=function(a){p=a;this.update()};return l},z=function(a){if(isNaN(a))return"";a=parseFloat(parseFloat(a).toFixed(4));return 0<a?"+"+a:a},ra=function(a,d){return a<d?(d-a)/Math.abs(a):a>d?-(a-d)/Math.abs(a):0},ka=function(a,d){var b=isNaN(a)||a===d?"":" ("+z((100*(a<d?(d-a)/Math.abs(a):a>d?-(a-d)/Math.abs(a):0)).toFixed(0))+"%)";return-1===
b.indexOf("Infinity")?b:" ("+z(d-a)+")"},sa=function(a){var d=A[a.preparationType],b=z(a.health*d),c=z(a.hunger*d),d=isNaN(a.sanity)?"":a.sanity*d;if(a.cook){var e=A[a.cook.preparationType];a.cook.health!==(a.health||0)&&(b+=" ("+z(a.cook.health*e-(b||0))+")");a.cook.hunger!==(a.hunger||0)&&(c+=" ("+z(a.cook.hunger*e-(c||0))+")");a.cook.sanity!==(a.sanity||0)&&(d+=" ("+z(a.cook.sanity*e-(d||0))+")")}return ja("td",a.img?a.img:"",qa(a.name),b,c,d,isNaN(a.perish)?"Never":a.perish/q+" "+ha("day",a.perish/
q),a.info||"")},ca=function(a,d,b,c){var e=A[a.preparationType]||1,f=a.health*e,g=a.hunger*e,e=a.sanity*e;return ja("td",a.img?a.img:"",qa(a.name),z(f)+ka(d,f),z(g)+ka(b,g),isNaN(e)?"":z(e)+ka(c,e),isNaN(a.perish)?"Never":a.perish/q+" "+ha("day",a.perish/q),(a.cooktime*wa+.5|0)+" secs",a.priority||"0",a.requires||"",a.note||"")};(function(){var a,d=[],b=[],c=function(a){return 0!==(a.modeMask&B)},e=U({"":"",Name:"name",Health:"health",Hunger:"hunger",Sanity:"sanity","Perish:Time to turn to rot":"perish",
Info:""},Array.prototype.slice.call(p),sa,"name",!1,function(c){c=c.target?"IMG"===c.target.tagName?c.target.parentNode.dataset.link:c.target.dataset.link:c;"recipe:"===c.substring(0,7)||"ingredient:"===c.substring(0,11)?(T("crockpot"),"recipe:"===c.substring(0,7)&&(c="*"+c.substring(7)),b=O(k,c),f.update(!0)):(a!==c?(a=c,d=O(p,c)):(a="",d.length=0),e.update(!0))},function(a){return-1!==d.indexOf(a)},c),f=U({"":"",Name:"name",Health:"health",Hunger:"hunger",Sanity:"sanity","Perish:Time to turn to rot":"perish",
"Cook Time":"cooktime","Priority:One of the highest priority recipes for a combination will be made":"priority","Requires:Dim, struck items cannot be used":"",Notes:""},Array.prototype.slice.call(k),ca,"name",!1,function(c){c=c.target?"IMG"===c.target.tagName?c.target.parentNode.dataset.link:c.target.dataset.link:c;var g=c.substring(c.indexOf(":")+1);x[g]?(b=O(k,c),f.update(!0)):(T("foodlist"),a=c,d=O(p,c),e.update(!0))},function(a){return-1!==b.indexOf(a)},c);Oa.appendChild(e);Pa.appendChild(f);
aa.push(function(){e.update();f.update()})})();var Ta=function(a,d){return a+"[ingredient:"+p[d.id].name+"|"+p[d.id].img+"]"},ta=function(a){var d=document.createElement("button");d.appendChild(document.createTextNode("Calculate efficient recipes (may take some time)"));d.className="makablebutton";d.addEventListener("click",function(){var b=[],c=a?a.length:null,e,f,g=[],h=[],m=[],n=function(a){return-1!==m.indexOf(a.id)},r=function(a){return-1!==this.indexOf(p[a])},q=function(a){-1!==m.indexOf(a.target.dataset.id)&&
m.splice(m.indexOf(a.target.dataset.id),1);-1!==h.indexOf(a.target.dataset.id)?(h.splice(h.indexOf(a.target.dataset.id),1),a.target.className=""):(h.push(a.target.dataset.id),a.target.className="selected");D.update()},v=function(a){-1!==h.indexOf(a.target.dataset.id)&&h.splice(h.indexOf(a.target.dataset.id),1);-1!==m.indexOf(a.target.dataset.id)?(m.splice(m.indexOf(a.target.dataset.id),1),a.target.className=""):(m.push(a.target.dataset.id),a.target.className="excluded");D.update();a.preventDefault()},
u=[],x=[],B=function(a){f&&(f.className="");for(var b=0;b<x.length;b++)x[b].className="";u.length=0;x.length=0;e===a.target.dataset.recipe?e=f=null:(e=a.target.dataset.recipe,f=a.target,a.target.className="selected");D.update()},t=function(a){f&&(f.className="",e=f=null);var b=x.indexOf(a.target);-1!==b?(u.splice(b,1),x.splice(b,1),a.target.className=""):(u.push(a.target.dataset.recipe),x.push(a.target),a.target.className="excluded");D.update();a.preventDefault()};null===c&&(c=p.length,a=p);for(;c--;)a[c].skip?
!a[c].cook||a[c].cook.uncookable||a[c].cook.skip||-1!==b.indexOf(a[c].cook)?!a[c].dry||a[c].dry.uncookable||a[c].dry.skip||-1!==b.indexOf(a[c].dry)||b.push(a[c].dry):b.push(a[c].cook):a[c].uncookable||a[c].cooked&&!a[c].ideal||a[c].rackdried&&!a[c].ideal||-1!==b.indexOf(a[c])||b.push(a[c]),!a[c].cooked||a[c].raw.uncookable||a[c].raw.skip||-1!==b.indexOf(a[c].raw)||b.push(a[c].raw),!a[c].rackdried||a[c].wet.uncookable||a[c].wet.skip||-1!==b.indexOf(a[c].wet)||b.push(a[c].wet);var C=[];var D=U({"":"",
Name:"name",Health:"health","Health+:Health gained compared to ingredients":"healthpls",Hunger:"hunger","Hunger+:Hunger gained compared to ingredients":"hungerpls",Ingredients:""},C,function(a){var b=a.recipe;return ja("td",b.img?b.img:"",b.name,z(b.health),z(a.healthpls)+" ("+z(100*a.healthpct|0)+"%)",z(b.hunger),z(a.hungerpls)+" ("+z(100*a.hungerpct|0)+"%)",fa(a.ingredients.reduce(Ta,"")+(a.multiple?"*":"")))},"hungerpls",!1,null,null,function(a){return(!e||a.recipe.name===e)&&(0===u.length||-1===
u.indexOf(a.recipe.name))&&(!m.length||!a.ingredients.some(n))&&(!h.length||h.every(r,a.ingredients))},0,15);var N=document.createElement("div");var W=document.createElement("div");W.appendChild(document.createTextNode("Computing combinations.."));c=document.createElement("div");c.appendChild(document.createTextNode("* combination has multiple possible results"));N.appendChild(W);var X=document.createElement("div");X.className="recipeFilter";N.appendChild(X);var F=document.createElement("div");F.className=
"foodFilter";b.forEach(function(a){var b=M(a.img,32);b.dataset.id=a.id;b.addEventListener("click",q,!1);b.addEventListener("contextmenu",v,!1);b.title=a.name;F.appendChild(b)});N.appendChild(F);var E=document.createElement("div");var A=document.createElement("input");A.type="text";A.placeholder="use custom filter";A.className="customFilterInput";E.appendChild(A);N.appendChild(D);d.parentNode.replaceChild(N,d);N.appendChild(c);Ra(b,function(a){var b;if(-1===g.indexOf(a.recipe.name)){for(b=0;b<g.length&&
!(a.recipe.name<g[b]);b++);g.splice(b,0,a.recipe.name);var c=M(k.byName(g[b].toLowerCase()).img);c.dataset.recipe=g[b];c.addEventListener("click",B,!1);c.addEventListener("contextmenu",t,!1);c.title=a.recipe.name;b<X.childNodes.length?X.insertBefore(c,X.childNodes[b]):X.appendChild(c)}a.name||(a.name=a.recipe.name,a.health=a.recipe.health,a.ihealth=a.tags.health,a.healthpls=a.recipe.health-a.ihealth,a.hunger=a.recipe.hunger,a.ihunger=a.tags.hunger,a.hungerpls=a.recipe.hunger-a.ihunger,a.healthpct=
ra(a.ihealth,a.recipe.health),a.hungerpct=ra(a.ihunger,a.recipe.hunger),a.sanity=a.recipe.sanity,a.perish=a.recipe.perish);C.push(a)},function(){W.firstChild.textContent="Found "+C.length+" valid recipes.. (you can change Food Guide tabs during this process)"},function(){D.setMaxRows(30);W.firstChild.textContent="Found "+C.length+" valid recipes. Showing top 30 for selected recipe using all selected ingredients. Right-click to exclude recipes or ingredients."})},!1);return d};document.getElementById("statistics").appendChild(ta());
var Ua=function(a,c){return a.reduce(function(a,d){return Math.max(a,d[c]||0)},-1E5)};window.food=p;window.recipes=k;window.matchingNames=O;var Y=function(a,c){if(null!==c)a.dataset.id=c.id;else{if(a.nextSibling&&null!==P(a.nextSibling)){Y(a,P(a.nextSibling));Y(a.nextSibling,null);return}a.dataset.id=null}null!==c?a.firstChild?a.replaceChild(M(c.img),a.firstChild):a.appendChild(M(c.img)):a.firstChild&&a.removeChild(a.firstChild);a.title=c?c.name:""},P=function(a){return a&&(p[a.dataset.id]||k[a.dataset.id]||
null)};(function(){for(var a=document.getElementsByClassName("ingredientpicker"),c=a.length;c--;)(function(){var b=document.createElement("span"),d=document.createElement("div"),e=document.createElement("ul"),f=a[c],g=c,h,m="recipes"===f.dataset.type?k:p,n=!f.dataset.cookable,r=f.nextSibling,q=r.getElementsByClassName("ingredient"),u=[],v,x=[],z=[],t=null,C=!1,D=document.getElementById("results"),A=document.getElementById("discoverfood"),B=document.getElementById("discover"),E=document.getElementById("makable"),
F=document.createElement("span"),G=function(a,b){for(var c=a;c.previousSibling;)if(c=c.previousSibling,b(c))return c;return null},J=function(a,b){for(var c=a;c.nextSibling;)if(c=c.nextSibling,b(c))return c;return null},H=!1,L=function(a){var b=p[a]||k[a]||null;if(da){for(a=0;a<q.length;a++)if(null===P(q[a]))return Y(q[a],b),C&&v(),a;return-1}-1===q.indexOf(a)&&(q.push(a),a=document.createElement("span"),a.className="ingredient",Y(a,b),a.addEventListener("click",R,!1),r.appendChild(a),C&&v());return 1},
Q=function(a){-1!==L(("IMG"===a.target.tagName?a.target.parentNode:a.target).dataset.id)&&a&&a.preventDefault&&a.preventDefault()},S=function(a){var b=M(a.img,32),c=document.createElement("span");c.appendChild(b);c.appendChild(document.createTextNode(a.name));c.dataset.id=a.id;-1!==u.indexOf(a)&&(c.style.opacity=.5);c.addEventListener("mousedown",Q,!1);this.appendChild(c);this.dataset.length++},T=function(a){-1!==u.indexOf(p[a.dataset.id])?a.style.opacity||(a.style.opacity=.5):a.style.opacity&&a.style.removeProperty("opacity")},
R=function(a){var b="IMG"===a.target.tagName?a.target.parentNode:a.target;if(da){if(null!==P(b))return Y(b,null),v(),b.dataset.id}else return a=q.indexOf(b.dataset.id),q.splice(a,1),r.removeChild(b),v(),q[a]||null},ba=function(){Z.splitTag();var a=O(m,Z.getSearch(),n);d.removeChild(e);e=document.createElement("div");e.dataset.length=0;a.forEach(S,e);d.appendChild(e);t=null},V=function(a){a="IMG"===a.target.tagName?a.target.parentNode.dataset.link:a.target.dataset.link;var b=O(m,a,n);1===b.length?
L(b[0].id):(f.value=a,ba())},I;"ingredients"===r.id?v=function(){u=Array.prototype.map.call(q,function(a){return P(a)});var a=Na(u);var b=a[0].health;var c=a[0].hunger;var d=a[0].sanity;var f=U({"":"",Name:"name",Health:"health",Hunger:"hunger",Sanity:"sanity","Perish:Time to turn to rot":"perish","Cook Time":"cooktime","Priority:One of the highest priority recipes for a combination will be made":"priority","Requires:Dim, struck items cannot be used":"",Notes:""},a,function(a){return ca(a,b,c,d)},
"priority",!0,V,function(a,b){return 0<b.length&&a.priority===Ua(b,"priority")});D.firstChild&&D.removeChild(D.firstChild);D.firstChild&&(D.removeChild(D.firstChild),D.removeChild(D.firstChild));D.appendChild(f);null!==u[0]&&(oa(x,u,a),0<x.length&&(D.appendChild(document.createTextNode("Add more ingredients to make:")),f=U({"":"",Name:"name","Health:(% more than ingredients)":"health","Hunger:(% more than ingredients)":"hunger",Sanity:"sanity","Perish:Time to turn to rot":"perish","Cook Time":"cooktime",
"Priority:One of the highest priority recipes for a combination will be made":"priority","Requires:Dim, struck items cannot be used":"",Notes:""},x,function(a){return ca(a,b,c,d)},"priority",!1,V),D.appendChild(f)));e&&e.firstChild&&Array.prototype.forEach.call(e.getElementsByTagName("span"),T)}:"inventory"===r.id&&(v=function(){u=Array.prototype.map.call(r.getElementsByClassName("ingredient"),function(a){return P(a)});A.firstChild&&A.removeChild(A.firstChild);B.firstChild&&B.removeChild(B.firstChild);
E.firstChild&&E.removeChild(E.firstChild);if(0<u.length){var a=U({"":"",Name:"name",Health:"health",Hunger:"hunger",Sanity:"sanity","Perish:Time to turn to rot":"perish",Info:""},u,sa,"name");A.appendChild(a);oa(z,u,null,!0);0<z.length&&(a=U({"":"",Name:"name",Health:"health",Hunger:"hunger",Sanity:"sanity","Perish:Time to turn to rot":"perish","Cook Time":"cooktime","Priority:One of the highest priority recipes for a combination will be made":"priority","Requires:Dim, struck items cannot be used":"",
Notes:""},z,ca,"name"),B.appendChild(a),E.appendChild(ta(u)))}e&&e.firstChild&&Array.prototype.forEach.call(e.getElementsByTagName("span"),T)});if(0!==q.length){var da=!0;Array.prototype.forEach.call(q,function(a){Y(a,null);a.addEventListener("click",R,!1)})}else q=[],da=!1;window.localStorage&&localStorage.foodGuideState&&(h=JSON.parse(localStorage.foodGuideState).pickers)&&h[g]&&h[g].forEach(function(a){p[a]&&L(a)});C=!0;b.className="searchselector retracted";b.appendChild(document.createTextNode("name"));
var Z=function(){var a=document.createElement("div"),c=!1,d=null,e=[{title:"name",prefix:"",placeholder:"Filter ingredients"},{title:"tag",prefix:"tag:",placeholder:"Meat, veggie, fruit, egg, monster..."},{title:"recipe",prefix:"recipe:",placeholder:"Find ingredients used in a recipe"}],g=e[0],h=null,k=function(){c=!1;a.style.height="0px";b.style.borderBottomLeftRadius="3px";a.style.borderTopLeftRadius="3px";null!==h&&(clearTimeout(h),h=null);b.className="searchselector retracted"},l=function(a){g=
a;f.placeholder=g.placeholder;b.firstChild.textContent=g.title},m=function(a){l(e[a.target.dataset.typeIndex]);ba();k()},n=/: */;b.addEventListener("click",function(){c?k():(null===d&&(a.style.height="auto",a.style.left=b.offsetLeft,a.style.top=b.offsetTop+b.offsetHeight,d=a.offsetHeight+"px",a.style.height="0px"),c=!0,a.style.height=d,b.style.borderBottomLeftRadius="0px",a.style.borderTopLeftRadius="0px",a.style.width="auto",a.style.width=Math.max(a.offsetWidth,b.offsetWidth+1)+"px",null!==h&&(clearTimeout(h),
h=null),b.className="searchselector extended")},!1);b.addEventListener("selectstart",function(a){a.preventDefault()},!1);b.addEventListener("mouseout",function(){null!==h&&clearTimeout(h);h=setTimeout(k,500)},!1);b.addEventListener("mouseover",function(){null!==h&&(clearTimeout(h),h=null)},!1);a.addEventListener("mouseout",function(){null!==h&&clearTimeout(h);h=setTimeout(k,500)},!1);a.addEventListener("mouseover",function(){null!==h&&(clearTimeout(h),h=null)},!1);e.forEach(function(b,c){var d=document.createElement("div");
d.appendChild(document.createTextNode(b.title));d.dataset.typeIndex=c;d.addEventListener("click",m,!1);b.element=d;a.appendChild(d)});f.parentNode.insertBefore(b,f);a.className="searchdropdown";f.parentNode.insertBefore(a,f);return{getTag:function(){return g.title},setSearchType:function(a){l(e[a])},getSearch:function(){return g.prefix+f.value},splitTag:function(){var a=f.value.split(n);if(2===a.length){var b=a[0].toLowerCase()+":";var c=a[1];for(a=0;a<e.length;a++)if(b===e[a].prefix){l(e[a]);f.value=
c;break}}}}}();d.className="ingredientdropdown";d.appendChild(e);d.addEventListener("mousedown",function(a){a.preventDefault()},!1);(function(){var a=O(m,Z.getSearch(),n);d.removeChild(e);e=document.createElement("div");e.dataset.length=0;a.forEach(S,e);d.appendChild(e)})();F.className="clearingredients";F.appendChild(document.createTextNode("clear"));F.addEventListener("click",function(){if(""===f.value&&"name"===Z.getTag())for(;P(r.firstChild);)R({target:r.firstChild});else f.value="",Z.setSearchType(0),
ba()},!1);F.addEventListener("mouseover",function(){""===f.value&&"name"===Z.getTag()&&(F.firstChild.textContent="clear chosen ingredients")},!1);F.addEventListener("mouseout",function(){"clear"!==F.firstChild.textContent&&(F.firstChild.textContent="clear")},!1);r.parentNode.insertBefore(F,r);r.parentNode.insertBefore(d,r);f.addEventListener("keydown",function(a){if(-1!==[16,17,37,38,39,40,13].indexOf(a.keyCode)){var b=t;13===a.keyCode?(null===t&&(t=e.firstChild||null),null!==t&&Q({target:t})):null===
t?40===a.keyCode&&(t=e.childNodes[1]||e.firstChild||null,null!==t&&(I=t.offsetLeft+t.offsetWidth/2,a.preventDefault())):(a.preventDefault(),37===a.keyCode?(t=t.previousSibling&&t.previousSibling.offsetTop===t.offsetTop?t.previousSibling:(a=J(t,function(a){return a.offsetTop!==t.offsetTop}))?a.previousSibling:e.lastChild,null!==t&&(I=t.offsetLeft+t.offsetWidth/2)):39===a.keyCode?(t=t.nextSibling&&t.nextSibling.offsetTop===t.offsetTop?t.nextSibling:(a=G(t,function(a){return a.offsetTop!==t.offsetTop}))?
a.nextSibling:e.firstChild,null!==t&&(I=t.offsetLeft+t.offsetWidth/2)):38===a.keyCode?((a=G(t,function(a){return I>=a.offsetLeft-1&&I<=a.offsetLeft+a.offsetWidth+1}))||(a=G(e.lastChild,function(a){return I>=a.offsetLeft-1&&I<=a.offsetLeft+a.offsetWidth+1})),t=a?a:e.firstChild):40===a.keyCode&&((a=J(t,function(a){return I>=a.offsetLeft-1&&I<=a.offsetLeft+a.offsetWidth+1}))||(a=J(e.firstChild,function(a){return I>=a.offsetLeft-1&&I<=a.offsetLeft+a.offsetWidth+1})),t=a?a:e.lastChild));t!==b&&(null!==
b&&(b.className=""),null!==t&&(t.className="selected"))}},!1);f.addEventListener("keyup",function(a){-1===[16,17,37,38,39,40,13].indexOf(a.keyCode)?ba():null!==t&&a.preventDefault()},!1);f.addEventListener("focus",function(){H||(H=!0)},!1);f.addEventListener("blur",function(){H&&(H=!1)},!1);v();window.addEventListener("beforeunload",function(){if(window.localStorage){localStorage.foodGuideState||(localStorage.foodGuideState="{}");var a=JSON.parse(localStorage.foodGuideState);a.pickers||(a.pickers=
[]);if(da){var b=[];b=Array.prototype.map.call(q,function(a){return(a=P(a))?a.id:null});a.pickers[g]=b}else a.pickers[g]=q;localStorage.foodGuideState=JSON.stringify(a)}});aa.push(ba);aa.push(v)})()})();var H=function(a){R(x[a.target.dataset.mode].mask)},u=function(a){R(B^x[a.target.dataset.mode].bit);a.preventDefault()},L=document.createElement("li");ga.insertBefore(L,ga.firstChild);L.className="mode";for(var la in x)f=M("img/"+x[la].img),f.dataset.mode=la,f.addEventListener("click",H,!1),f.addEventListener("contextmenu",
u,!1),f.title=x[la].name+"\nleft-click to select\nright-click to toggle",L.appendChild(f);R(B)})();